
version: 1.0.0
client:
  organization: Org1
  logging:
    level: debug
  cryptoconfig:
    path: Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config
  credentialStore:
    path: /tmp/Org1/state-store
    cryptoStore:
      path: /tmp/Org1/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: SW
      hashAlgorithm: SHA2
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: /crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: /crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt
channels:
  mychannel1:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 8
        peerMonitorPeriod: 6s
organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: /fabric/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
  ordererorg:
    mspID: OrdererMSP
    cryptoPath: /fabric/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
orderers:
  orderer0.example.com:
    url: grpc://orderer0.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer0.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
  orderer1.example.com:
    url: grpc://orderer1.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
peers:
  peer0.org1.example.com:
    url: grpc://peer0.org1.example.com:7051
    eventUrl: grpc://peer0.org1.example.com:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
  peer1.org1.example.com:
    url: grpc://peer1.org1.example.com:7051
    eventUrl: grpc://peer1.org1.example.com:7053
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
certificateAuthorities:
  ca.org1.example.com:
    url: https://ca.org1.example.com:7054
    caName: admin
    tlsCACerts:
      path: peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
      client:
        key:
          path: peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
        cert:
          path: peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt
    registrar:
      enrollId: adminpw
      enrollSecret: ca.org1.example.com
  ca.org2.example.com:
    url: https://ca.org2.example.com:7054
    caName: admin
    tlsCACerts:
      path: peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
      client:
        key:
          path: peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.key
        cert:
          path: peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.crt
    registrar:
      enrollId: adminpw
      enrollSecret: ca.org2.example.com
