version: 1.0.0
client:
  organization: Org1
  logging:
    level: debug
  cryptoconfig:
    path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config
  credentialStore:
    path: /tmp/Org1/state-store
    cryptoStore:
      path: /tmp/Org1/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: SW
      hashAlgorithm: SHA2
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: false
    client:
      key:
        path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/users/Admin@league01-org1-vh-cn/tls/client.key
      cert:
        path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/users/Admin@league01-org1-vh-cn/tls/client.crt
channels:
  mychannel:
    peers:
      peer0.league01-org1-vh-cn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 8
        peerMonitorPeriod: 6s
organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/users/Admin@league01-org1-vh-cn/msp
    peers:
      - peer0.league01-org1-vh-cn
    certificateAuthorities:
      - ca0.league01-org1-vh-cn
  ordererorg:
    mspID: OrdererMSP
    cryptoPath: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/ordererOrganizations/league01-vh-cn/users/Admin@league01-vh-cn/msp
orderers:
  order0.league01-vh-cn:7050:
    url: grpc://10.10.203.51:30054
    grpcOptions:
      ssl-target-name-override: order0.league01-vh-cn
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/ordererOrganizations/league01-vh-cn/tlsca/tlsca.league01-vh-cn-cert.pem
peers:
  peer0.league01-org1-vh-cn:
    url: grpc://10.10.203.51:30056
    eventUrl: grpc://10.10.203.51:30058
    grpcOptions:
      ssl-target-name-override: peer0.league01-org1-vh-cn
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/tlsca/tlsca.league01-org1-vh-cn-cert.pem
certificateAuthorities:
  ca.league01-vh-cn:
    url: https://10.10.203.51:30059
    caName: admin
    tlsCACerts:
      path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/tlsca/tlsca.league01-org1-vh-cn-cert.pem
      client:
        key:
          path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/users/Admin@league01-org1-vh-cn/tls/client.key
        cert:
          path: /Users/aberic/Documents/path/go/src/github.com/ennoo/fabric-client/fabric/example/config/crypto-config/peerOrganizations/league01-org1-vh-cn/users/Admin@league01-org1-vh-cn/tls/client.crt
    registrar:
      enrollId: adminpw
      enrollSecret: ca.league01-vh-cn