version: "3"

services:
  operation:
    image: ennoo/fabric-client:latest
    ports:
      - 19865:19865
      - 19877:19877
    environment:
      - PROTOCOL=BOTH
    volumes:
      - /data/mount/dev/chain:/home/data
    networks:
      - tmp
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  tmp:
    driver: overlay