// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/chain/channel.proto

package chain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChannelCreate struct {
	ConfigID             string   `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	OrderOrgName         string   `protobuf:"bytes,2,opt,name=orderOrgName,proto3" json:"orderOrgName,omitempty"`
	OrgName              string   `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgUser              string   `protobuf:"bytes,4,opt,name=orgUser,proto3" json:"orgUser,omitempty"`
	ChannelID            string   `protobuf:"bytes,5,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ChannelConfigPath    string   `protobuf:"bytes,6,opt,name=channelConfigPath,proto3" json:"channelConfigPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelCreate) Reset()         { *m = ChannelCreate{} }
func (m *ChannelCreate) String() string { return proto.CompactTextString(m) }
func (*ChannelCreate) ProtoMessage()    {}
func (*ChannelCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba4cdd5356e4d30, []int{0}
}

func (m *ChannelCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelCreate.Unmarshal(m, b)
}
func (m *ChannelCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelCreate.Marshal(b, m, deterministic)
}
func (m *ChannelCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelCreate.Merge(m, src)
}
func (m *ChannelCreate) XXX_Size() int {
	return xxx_messageInfo_ChannelCreate.Size(m)
}
func (m *ChannelCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelCreate proto.InternalMessageInfo

func (m *ChannelCreate) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *ChannelCreate) GetOrderOrgName() string {
	if m != nil {
		return m.OrderOrgName
	}
	return ""
}

func (m *ChannelCreate) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *ChannelCreate) GetOrgUser() string {
	if m != nil {
		return m.OrgUser
	}
	return ""
}

func (m *ChannelCreate) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelCreate) GetChannelConfigPath() string {
	if m != nil {
		return m.ChannelConfigPath
	}
	return ""
}

type ChannelJoin struct {
	ConfigID             string   `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	OrderName            string   `protobuf:"bytes,2,opt,name=orderName,proto3" json:"orderName,omitempty"`
	OrgName              string   `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgUser              string   `protobuf:"bytes,4,opt,name=orgUser,proto3" json:"orgUser,omitempty"`
	ChannelID            string   `protobuf:"bytes,5,opt,name=channelID,proto3" json:"channelID,omitempty"`
	PeerUrl              string   `protobuf:"bytes,6,opt,name=peerUrl,proto3" json:"peerUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelJoin) Reset()         { *m = ChannelJoin{} }
func (m *ChannelJoin) String() string { return proto.CompactTextString(m) }
func (*ChannelJoin) ProtoMessage()    {}
func (*ChannelJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba4cdd5356e4d30, []int{1}
}

func (m *ChannelJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelJoin.Unmarshal(m, b)
}
func (m *ChannelJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelJoin.Marshal(b, m, deterministic)
}
func (m *ChannelJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelJoin.Merge(m, src)
}
func (m *ChannelJoin) XXX_Size() int {
	return xxx_messageInfo_ChannelJoin.Size(m)
}
func (m *ChannelJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelJoin proto.InternalMessageInfo

func (m *ChannelJoin) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *ChannelJoin) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

func (m *ChannelJoin) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *ChannelJoin) GetOrgUser() string {
	if m != nil {
		return m.OrgUser
	}
	return ""
}

func (m *ChannelJoin) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelJoin) GetPeerUrl() string {
	if m != nil {
		return m.PeerUrl
	}
	return ""
}

type ChannelList struct {
	ConfigID             string   `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	OrgName              string   `protobuf:"bytes,2,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgUser              string   `protobuf:"bytes,3,opt,name=orgUser,proto3" json:"orgUser,omitempty"`
	PeerName             string   `protobuf:"bytes,4,opt,name=peerName,proto3" json:"peerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelList) Reset()         { *m = ChannelList{} }
func (m *ChannelList) String() string { return proto.CompactTextString(m) }
func (*ChannelList) ProtoMessage()    {}
func (*ChannelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba4cdd5356e4d30, []int{2}
}

func (m *ChannelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelList.Unmarshal(m, b)
}
func (m *ChannelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelList.Marshal(b, m, deterministic)
}
func (m *ChannelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelList.Merge(m, src)
}
func (m *ChannelList) XXX_Size() int {
	return xxx_messageInfo_ChannelList.Size(m)
}
func (m *ChannelList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelList.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelList proto.InternalMessageInfo

func (m *ChannelList) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *ChannelList) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *ChannelList) GetOrgUser() string {
	if m != nil {
		return m.OrgUser
	}
	return ""
}

func (m *ChannelList) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func init() {
	proto.RegisterType((*ChannelCreate)(nil), "chain.ChannelCreate")
	proto.RegisterType((*ChannelJoin)(nil), "chain.ChannelJoin")
	proto.RegisterType((*ChannelList)(nil), "chain.ChannelList")
}

func init() { proto.RegisterFile("grpc/proto/chain/channel.proto", fileDescriptor_4ba4cdd5356e4d30) }

var fileDescriptor_4ba4cdd5356e4d30 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0x6b, 0xff, 0xae, 0x15, 0x74, 0x56, 0x43, 0x29, 0x22, 0xd9, 0xe8, 0x42, 0xd3,
	0x85, 0x6f, 0xd0, 0x74, 0x13, 0x11, 0x2d, 0x42, 0x37, 0xee, 0xd2, 0xf1, 0x36, 0x1d, 0x88, 0x33,
	0xe1, 0x76, 0x36, 0x3e, 0x97, 0x0f, 0xe2, 0x2b, 0xc9, 0xdc, 0x4c, 0xd3, 0x56, 0xb1, 0x3b, 0x37,
	0x81, 0x73, 0xbe, 0x84, 0x7c, 0x17, 0x0e, 0x5c, 0x16, 0x54, 0xa9, 0x49, 0x45, 0xd6, 0xd9, 0x89,
	0x5a, 0xe7, 0xda, 0xf8, 0xa7, 0x31, 0x58, 0x26, 0xdc, 0x89, 0x0e, 0x97, 0xf1, 0x57, 0x04, 0x67,
	0x69, 0x0d, 0x52, 0xc2, 0xdc, 0xa1, 0x18, 0x41, 0x5f, 0x59, 0xb3, 0xd2, 0x45, 0x36, 0x93, 0xd1,
	0x55, 0x74, 0x33, 0x78, 0x69, 0xb2, 0x88, 0x61, 0x68, 0xe9, 0x0d, 0xe9, 0x99, 0x8a, 0xa7, 0xfc,
	0x1d, 0x65, 0x8b, 0xf9, 0x41, 0x27, 0x24, 0xf4, 0x6c, 0xc0, 0x6d, 0xc6, 0xdb, 0x18, 0xc8, 0x62,
	0x83, 0x24, 0x4f, 0x1a, 0xe2, 0xa3, 0x18, 0xc3, 0x20, 0xd8, 0x65, 0x33, 0xd9, 0x61, 0xb6, 0x2b,
	0xc4, 0x2d, 0x5c, 0x84, 0x90, 0xb2, 0xc8, 0x3c, 0x77, 0x6b, 0xd9, 0xe5, 0xb7, 0x7e, 0x83, 0xf8,
	0x33, 0x82, 0xd3, 0x70, 0xd1, 0x83, 0xd5, 0xe6, 0xe8, 0x3d, 0x63, 0x18, 0xb0, 0xfb, 0xde, 0x31,
	0xbb, 0xe2, 0x1f, 0x2e, 0x91, 0xd0, 0xab, 0x10, 0x69, 0x41, 0x65, 0xf0, 0xdf, 0xc6, 0xf8, 0xa3,
	0x91, 0x7e, 0xd4, 0x1b, 0x77, 0x54, 0x7a, 0x4f, 0xab, 0xf5, 0xa7, 0x56, 0xfb, 0x50, 0x6b, 0x04,
	0x7d, 0xff, 0x27, 0xfe, 0xa8, 0x36, 0x6e, 0xf2, 0x34, 0x83, 0x6b, 0x6d, 0x13, 0x34, 0xc6, 0xda,
	0x64, 0x95, 0x2f, 0x49, 0xab, 0x3b, 0x55, 0x6a, 0x34, 0x2e, 0xf1, 0x13, 0xaa, 0xe7, 0x92, 0xf0,
	0x5a, 0xa6, 0xc3, 0xe0, 0x38, 0xf7, 0xdd, 0xeb, 0xf9, 0xcf, 0x89, 0x2d, 0xbb, 0x1c, 0xee, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xa6, 0xb1, 0x6d, 0x7d, 0x02, 0x00, 0x00,
}
