// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/chain/server.proto

package chain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("grpc/proto/chain/server.proto", fileDescriptor_3248a815c2f630c6) }

var fileDescriptor_3248a815c2f630c6 = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xcf, 0x73, 0x1b, 0x35,
	0x14, 0xc7, 0xcd, 0x10, 0x02, 0x7e, 0x89, 0x63, 0x8f, 0x0c, 0x01, 0x36, 0x21, 0x18, 0xc3, 0x0c,
	0x0c, 0x09, 0x36, 0xe3, 0x30, 0xe4, 0x90, 0x03, 0xd8, 0x0a, 0x24, 0x0e, 0x99, 0x71, 0x88, 0x9b,
	0xb6, 0xd3, 0xdb, 0x66, 0x57, 0x5e, 0x6b, 0xb2, 0x95, 0x1c, 0xad, 0xec, 0xa9, 0xfb, 0x9f, 0xf4,
	0xd0, 0x7b, 0xff, 0xc8, 0x1e, 0x3a, 0xd2, 0xfe, 0xf0, 0x7a, 0x25, 0xbb, 0x39, 0xea, 0xfb, 0xde,
	0xf7, 0xf3, 0x9e, 0x9e, 0xa5, 0xb5, 0xe0, 0xbb, 0x40, 0x4c, 0xbc, 0xf6, 0x44, 0x70, 0xc9, 0xdb,
	0xde, 0xd8, 0xa5, 0xac, 0x1d, 0x11, 0x31, 0x23, 0xa2, 0xa5, 0x25, 0xf4, 0x99, 0xd6, 0x1c, 0x33,
	0x4b, 0x90, 0x68, 0x1a, 0xca, 0x38, 0xcb, 0x39, 0x30, 0xc2, 0xde, 0xd8, 0x65, 0x8c, 0x84, 0x49,
	0xbc, 0x61, 0x8b, 0x53, 0xe6, 0x71, 0x9f, 0x24, 0x19, 0x66, 0x81, 0x90, 0xf8, 0x41, 0xda, 0x86,
	0x25, 0xec, 0x71, 0x36, 0xa2, 0x41, 0x1c, 0xee, 0xbc, 0xfd, 0x04, 0x2a, 0x57, 0x3a, 0x1f, 0xc7,
	0x75, 0x51, 0x1b, 0x36, 0xb1, 0x20, 0xae, 0x24, 0xe8, 0xcb, 0x96, 0x36, 0xb4, 0x92, 0x48, 0xac,
	0x3a, 0x95, 0x44, 0x1d, 0x4a, 0x41, 0x59, 0xd0, 0x2c, 0xa1, 0x43, 0xd8, 0xb8, 0xe4, 0x94, 0x21,
	0xb4, 0x9c, 0xae, 0x34, 0x33, 0xb9, 0x05, 0x1b, 0x57, 0x34, 0x92, 0xc5, 0x64, 0xa5, 0x39, 0xb5,
	0xa5, 0xe4, 0xae, 0x10, 0xcd, 0x52, 0xe7, 0xcd, 0xa7, 0x50, 0xcd, 0xfa, 0xa3, 0x0c, 0x73, 0x9f,
	0xa0, 0x23, 0x28, 0xf7, 0x59, 0x24, 0xdd, 0x30, 0xc4, 0x18, 0xed, 0x24, 0xa6, 0x44, 0x31, 0x2b,
	0xfe, 0x0e, 0x5b, 0x49, 0x8c, 0xf8, 0x18, 0xa3, 0xda, 0x72, 0x3e, 0xf1, 0x33, 0x07, 0xc6, 0xaa,
	0x8b, 0x66, 0x09, 0xfd, 0x01, 0x15, 0x1d, 0x65, 0x92, 0xba, 0x92, 0x60, 0x9c, 0x35, 0x9b, 0x53,
	0xcd, 0x3a, 0x7f, 0xc2, 0x4e, 0x2e, 0xae, 0x4a, 0xd5, 0x4d, 0x9b, 0xa5, 0xda, 0x11, 0x94, 0x6f,
	0x27, 0x81, 0x70, 0x7d, 0x92, 0xdb, 0x4d, 0xa2, 0x98, 0x55, 0x7e, 0x85, 0x2f, 0xfa, 0x6c, 0xc6,
	0xef, 0x55, 0x72, 0x25, 0xe3, 0x2b, 0xc1, 0xcc, 0xd5, 0xfb, 0x88, 0x73, 0xbb, 0xd1, 0x9c, 0x79,
	0xb9, 0x7d, 0x28, 0x55, 0x6b, 0xa6, 0xeb, 0x17, 0xf8, 0xfc, 0xff, 0x29, 0x11, 0x73, 0x8c, 0xd1,
	0x76, 0x12, 0xd3, 0x6b, 0x23, 0xb3, 0xf3, 0x6e, 0x03, 0x36, 0xe3, 0xdf, 0x06, 0x9d, 0x40, 0x55,
	0x27, 0xc5, 0xcb, 0x3e, 0x1b, 0xf1, 0x6c, 0x2b, 0x37, 0xe4, 0x41, 0xad, 0x9d, 0xc2, 0x2f, 0xae,
	0xb4, 0x66, 0x09, 0x61, 0xf8, 0x26, 0x67, 0xec, 0x85, 0xdc, 0xbb, 0xef, 0xcd, 0x2f, 0x08, 0x0d,
	0xc6, 0x12, 0x7d, 0xbd, 0x20, 0x2c, 0x05, 0x9c, 0xb4, 0x2f, 0xad, 0x36, 0x4b, 0xe8, 0x2f, 0xd8,
	0xb5, 0x40, 0xdc, 0x68, 0x8c, 0xbe, 0x32, 0x11, 0x6e, 0x34, 0x7e, 0x1c, 0xe0, 0xc9, 0xab, 0xfe,
	0x99, 0x05, 0xa0, 0x64, 0x0b, 0xa0, 0x5e, 0xd8, 0xff, 0x70, 0x42, 0x16, 0x03, 0x4f, 0x66, 0xa0,
	0xb4, 0x15, 0x73, 0xf8, 0x0f, 0xf6, 0x57, 0xcd, 0x41, 0x93, 0xf6, 0x56, 0xcc, 0x42, 0x23, 0x8b,
	0xdd, 0x9c, 0x83, 0x63, 0x9f, 0x87, 0x46, 0x7d, 0x6b, 0x9d, 0xc9, 0xe3, 0x41, 0x6a, 0x00, 0x2b,
	0x40, 0x69, 0xa8, 0x08, 0xea, 0xbc, 0x2f, 0xc3, 0x76, 0x72, 0x8d, 0xf5, 0xd7, 0x07, 0x1d, 0x42,
	0xf9, 0x9c, 0xc8, 0x64, 0xb1, 0x7c, 0xb2, 0x16, 0x57, 0x44, 0x47, 0x9b, 0x25, 0xd4, 0x06, 0xe8,
	0x33, 0x2a, 0x71, 0x48, 0x09, 0x93, 0xd9, 0x0d, 0xbe, 0x21, 0x0f, 0xb1, 0x62, 0x9e, 0xe1, 0x13,
	0x75, 0x17, 0x53, 0xc3, 0x90, 0x84, 0xa3, 0xec, 0x5b, 0x96, 0x99, 0x94, 0x6a, 0x1a, 0x4f, 0xa1,
	0xb6, 0x30, 0xe2, 0x69, 0x24, 0xf9, 0x4b, 0xb4, 0x5b, 0xb4, 0xc6, 0xba, 0x69, 0xfe, 0x1b, 0x76,
	0xbb, 0xbe, 0x3f, 0x10, 0x43, 0x22, 0xaf, 0x09, 0x11, 0xff, 0xf2, 0xec, 0x9b, 0x9a, 0x3b, 0x45,
	0x89, 0xa4, 0x12, 0x4c, 0xc2, 0x2d, 0xfc, 0x94, 0x12, 0xe2, 0x3b, 0x98, 0x24, 0xf3, 0x90, 0x7a,
	0xf3, 0x1c, 0x6f, 0xdf, 0xe4, 0xe9, 0x14, 0xfb, 0x45, 0x45, 0x4f, 0xe1, 0x87, 0x14, 0x7b, 0x46,
	0x23, 0x8f, 0xcf, 0x88, 0x98, 0x1b, 0xcc, 0xc6, 0x0a, 0x66, 0xe6, 0x58, 0xdb, 0xee, 0x3f, 0x33,
	0x3d, 0x53, 0x31, 0xa3, 0x1e, 0x79, 0x74, 0xbb, 0xda, 0x64, 0x62, 0xaf, 0xe1, 0xfb, 0x14, 0x3b,
	0x10, 0x3e, 0x11, 0x7a, 0x94, 0x03, 0x11, 0xb8, 0x8c, 0xbe, 0x76, 0x25, 0xe5, 0x2c, 0xca, 0x13,
	0x97, 0x02, 0x3a, 0xdf, 0x24, 0x3e, 0x87, 0x1f, 0x3f, 0x42, 0xd4, 0x87, 0xa4, 0xb1, 0x8e, 0x6a,
	0x3f, 0x30, 0x97, 0xb0, 0xb7, 0x20, 0x07, 0x46, 0x9f, 0xce, 0x4a, 0x62, 0x60, 0xb2, 0x6e, 0xf2,
	0xfb, 0x0e, 0xac, 0x1d, 0x1e, 0xac, 0xe6, 0xd9, 0xfb, 0x3b, 0x86, 0x6a, 0x61, 0xe7, 0xa8, 0x9a,
	0x67, 0x58, 0xc7, 0x75, 0x0a, 0xf5, 0x82, 0x49, 0x17, 0xaf, 0x17, 0x8c, 0xf6, 0x8a, 0x6d, 0xd8,
	0xce, 0xdf, 0x82, 0xfc, 0xff, 0x80, 0xfd, 0xd0, 0x9f, 0x40, 0x2d, 0x6f, 0xd0, 0xa5, 0xd0, 0xb2,
	0xc9, 0x5e, 0x69, 0x00, 0xfb, 0xa9, 0x11, 0x13, 0x21, 0xe9, 0x88, 0x7a, 0xae, 0x24, 0xdd, 0xa9,
	0x1c, 0x73, 0x41, 0xe5, 0x3c, 0x3f, 0x2c, 0x5b, 0xdc, 0x04, 0x3e, 0x83, 0xc6, 0x3a, 0xa0, 0xee,
	0xac, 0xb9, 0x1e, 0x6a, 0xed, 0xb4, 0x77, 0x01, 0x3f, 0x53, 0xde, 0x22, 0x8c, 0x71, 0xde, 0x1a,
	0xb9, 0x77, 0x82, 0x7a, 0xbf, 0x79, 0xfa, 0x53, 0xd2, 0x52, 0xaf, 0xb3, 0xf8, 0x29, 0x16, 0x7b,
	0x7a, 0x5b, 0x43, 0xfd, 0x88, 0xbc, 0x56, 0xd2, 0x8b, 0x5a, 0xf1, 0xf1, 0x76, 0xb7, 0xa9, 0x17,
	0xc7, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa1, 0xf9, 0x55, 0x7d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LedgerChannelClient is the client API for LedgerChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerChannelClient interface {
	Create(ctx context.Context, in *ChannelCreate, opts ...grpc.CallOption) (*String, error)
	Join(ctx context.Context, in *ChannelJoin, opts ...grpc.CallOption) (*String, error)
	List(ctx context.Context, in *ChannelList, opts ...grpc.CallOption) (*StringArr, error)
}

type ledgerChannelClient struct {
	cc *grpc.ClientConn
}

func NewLedgerChannelClient(cc *grpc.ClientConn) LedgerChannelClient {
	return &ledgerChannelClient{cc}
}

func (c *ledgerChannelClient) Create(ctx context.Context, in *ChannelCreate, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChannel/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChannelClient) Join(ctx context.Context, in *ChannelJoin, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChannel/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChannelClient) List(ctx context.Context, in *ChannelList, opts ...grpc.CallOption) (*StringArr, error) {
	out := new(StringArr)
	err := c.cc.Invoke(ctx, "/chain.LedgerChannel/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerChannelServer is the server API for LedgerChannel service.
type LedgerChannelServer interface {
	Create(context.Context, *ChannelCreate) (*String, error)
	Join(context.Context, *ChannelJoin) (*String, error)
	List(context.Context, *ChannelList) (*StringArr, error)
}

func RegisterLedgerChannelServer(s *grpc.Server, srv LedgerChannelServer) {
	s.RegisterService(&_LedgerChannel_serviceDesc, srv)
}

func _LedgerChannel_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChannelServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChannel/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChannelServer).Create(ctx, req.(*ChannelCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChannel_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChannelServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChannel/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChannelServer).Join(ctx, req.(*ChannelJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChannel_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChannelServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChannel/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChannelServer).List(ctx, req.(*ChannelList))
	}
	return interceptor(ctx, in, info, handler)
}

var _LedgerChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.LedgerChannel",
	HandlerType: (*LedgerChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LedgerChannel_Create_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _LedgerChannel_Join_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LedgerChannel_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/chain/server.proto",
}

// LedgerChainCodeClient is the client API for LedgerChainCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerChainCodeClient interface {
	InstallCC(ctx context.Context, in *Install, opts ...grpc.CallOption) (*String, error)
	InstalledCC(ctx context.Context, in *Installed, opts ...grpc.CallOption) (*CCList, error)
	InstantiateCC(ctx context.Context, in *Instantiate, opts ...grpc.CallOption) (*String, error)
	InstantiatedCC(ctx context.Context, in *Instantiated, opts ...grpc.CallOption) (*CCList, error)
	UpgradeCC(ctx context.Context, in *Upgrade, opts ...grpc.CallOption) (*String, error)
	InvokeCC(ctx context.Context, in *Invoke, opts ...grpc.CallOption) (*String, error)
	InvokeCCAsync(ctx context.Context, in *InvokeAsync, opts ...grpc.CallOption) (*String, error)
	QueryCC(ctx context.Context, in *Query, opts ...grpc.CallOption) (*String, error)
}

type ledgerChainCodeClient struct {
	cc *grpc.ClientConn
}

func NewLedgerChainCodeClient(cc *grpc.ClientConn) LedgerChainCodeClient {
	return &ledgerChainCodeClient{cc}
}

func (c *ledgerChainCodeClient) InstallCC(ctx context.Context, in *Install, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InstallCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) InstalledCC(ctx context.Context, in *Installed, opts ...grpc.CallOption) (*CCList, error) {
	out := new(CCList)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InstalledCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) InstantiateCC(ctx context.Context, in *Instantiate, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InstantiateCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) InstantiatedCC(ctx context.Context, in *Instantiated, opts ...grpc.CallOption) (*CCList, error) {
	out := new(CCList)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InstantiatedCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) UpgradeCC(ctx context.Context, in *Upgrade, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/UpgradeCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) InvokeCC(ctx context.Context, in *Invoke, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InvokeCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) InvokeCCAsync(ctx context.Context, in *InvokeAsync, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/InvokeCCAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerChainCodeClient) QueryCC(ctx context.Context, in *Query, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerChainCode/QueryCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerChainCodeServer is the server API for LedgerChainCode service.
type LedgerChainCodeServer interface {
	InstallCC(context.Context, *Install) (*String, error)
	InstalledCC(context.Context, *Installed) (*CCList, error)
	InstantiateCC(context.Context, *Instantiate) (*String, error)
	InstantiatedCC(context.Context, *Instantiated) (*CCList, error)
	UpgradeCC(context.Context, *Upgrade) (*String, error)
	InvokeCC(context.Context, *Invoke) (*String, error)
	InvokeCCAsync(context.Context, *InvokeAsync) (*String, error)
	QueryCC(context.Context, *Query) (*String, error)
}

func RegisterLedgerChainCodeServer(s *grpc.Server, srv LedgerChainCodeServer) {
	s.RegisterService(&_LedgerChainCode_serviceDesc, srv)
}

func _LedgerChainCode_InstallCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Install)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InstallCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InstallCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InstallCC(ctx, req.(*Install))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_InstalledCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Installed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InstalledCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InstalledCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InstalledCC(ctx, req.(*Installed))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_InstantiateCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instantiate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InstantiateCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InstantiateCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InstantiateCC(ctx, req.(*Instantiate))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_InstantiatedCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instantiated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InstantiatedCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InstantiatedCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InstantiatedCC(ctx, req.(*Instantiated))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_UpgradeCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Upgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).UpgradeCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/UpgradeCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).UpgradeCC(ctx, req.(*Upgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_InvokeCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InvokeCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InvokeCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InvokeCC(ctx, req.(*Invoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_InvokeCCAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeAsync)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).InvokeCCAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/InvokeCCAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).InvokeCCAsync(ctx, req.(*InvokeAsync))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerChainCode_QueryCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerChainCodeServer).QueryCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerChainCode/QueryCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerChainCodeServer).QueryCC(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _LedgerChainCode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.LedgerChainCode",
	HandlerType: (*LedgerChainCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallCC",
			Handler:    _LedgerChainCode_InstallCC_Handler,
		},
		{
			MethodName: "InstalledCC",
			Handler:    _LedgerChainCode_InstalledCC_Handler,
		},
		{
			MethodName: "InstantiateCC",
			Handler:    _LedgerChainCode_InstantiateCC_Handler,
		},
		{
			MethodName: "InstantiatedCC",
			Handler:    _LedgerChainCode_InstantiatedCC_Handler,
		},
		{
			MethodName: "UpgradeCC",
			Handler:    _LedgerChainCode_UpgradeCC_Handler,
		},
		{
			MethodName: "InvokeCC",
			Handler:    _LedgerChainCode_InvokeCC_Handler,
		},
		{
			MethodName: "InvokeCCAsync",
			Handler:    _LedgerChainCode_InvokeCCAsync_Handler,
		},
		{
			MethodName: "QueryCC",
			Handler:    _LedgerChainCode_QueryCC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/chain/server.proto",
}

// LedgerClient is the client API for Ledger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerClient interface {
	QueryLedgerInfo(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*ChannelInfo, error)
	QueryLedgerBlockByHeight(ctx context.Context, in *ReqBlockByHeight, opts ...grpc.CallOption) (*Block, error)
	QueryLedgerBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*Block, error)
	QueryLedgerBlockByTxID(ctx context.Context, in *ReqBlockByTxID, opts ...grpc.CallOption) (*Block, error)
	QueryLedgerInfoSpec(ctx context.Context, in *ReqInfoSpec, opts ...grpc.CallOption) (*ChannelInfo, error)
	QueryLedgerBlockByHeightSpec(ctx context.Context, in *ReqBlockByHeightSpec, opts ...grpc.CallOption) (*Block, error)
	QueryLedgerBlockByHashSpec(ctx context.Context, in *ReqBlockByHashSpec, opts ...grpc.CallOption) (*Block, error)
	QueryLedgerBlockByTxIDSpec(ctx context.Context, in *ReqBlockByTxIDSpec, opts ...grpc.CallOption) (*Block, error)
}

type ledgerClient struct {
	cc *grpc.ClientConn
}

func NewLedgerClient(cc *grpc.ClientConn) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) QueryLedgerInfo(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*ChannelInfo, error) {
	out := new(ChannelInfo)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByHeight(ctx context.Context, in *ReqBlockByHeight, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByTxID(ctx context.Context, in *ReqBlockByTxID, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByTxID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerInfoSpec(ctx context.Context, in *ReqInfoSpec, opts ...grpc.CallOption) (*ChannelInfo, error) {
	out := new(ChannelInfo)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerInfoSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByHeightSpec(ctx context.Context, in *ReqBlockByHeightSpec, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByHeightSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByHashSpec(ctx context.Context, in *ReqBlockByHashSpec, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByHashSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryLedgerBlockByTxIDSpec(ctx context.Context, in *ReqBlockByTxIDSpec, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/chain.Ledger/QueryLedgerBlockByTxIDSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServer is the server API for Ledger service.
type LedgerServer interface {
	QueryLedgerInfo(context.Context, *ReqInfo) (*ChannelInfo, error)
	QueryLedgerBlockByHeight(context.Context, *ReqBlockByHeight) (*Block, error)
	QueryLedgerBlockByHash(context.Context, *ReqBlockByHash) (*Block, error)
	QueryLedgerBlockByTxID(context.Context, *ReqBlockByTxID) (*Block, error)
	QueryLedgerInfoSpec(context.Context, *ReqInfoSpec) (*ChannelInfo, error)
	QueryLedgerBlockByHeightSpec(context.Context, *ReqBlockByHeightSpec) (*Block, error)
	QueryLedgerBlockByHashSpec(context.Context, *ReqBlockByHashSpec) (*Block, error)
	QueryLedgerBlockByTxIDSpec(context.Context, *ReqBlockByTxIDSpec) (*Block, error)
}

func RegisterLedgerServer(s *grpc.Server, srv LedgerServer) {
	s.RegisterService(&_Ledger_serviceDesc, srv)
}

func _Ledger_QueryLedgerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerInfo(ctx, req.(*ReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHeight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByHeight(ctx, req.(*ReqBlockByHeight))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByHash(ctx, req.(*ReqBlockByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByTxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByTxID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByTxID(ctx, req.(*ReqBlockByTxID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerInfoSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqInfoSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerInfoSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerInfoSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerInfoSpec(ctx, req.(*ReqInfoSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByHeightSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHeightSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByHeightSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByHeightSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByHeightSpec(ctx, req.(*ReqBlockByHeightSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByHashSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHashSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByHashSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByHashSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByHashSpec(ctx, req.(*ReqBlockByHashSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryLedgerBlockByTxIDSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByTxIDSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryLedgerBlockByTxIDSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.Ledger/QueryLedgerBlockByTxIDSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryLedgerBlockByTxIDSpec(ctx, req.(*ReqBlockByTxIDSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ledger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryLedgerInfo",
			Handler:    _Ledger_QueryLedgerInfo_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByHeight",
			Handler:    _Ledger_QueryLedgerBlockByHeight_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByHash",
			Handler:    _Ledger_QueryLedgerBlockByHash_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByTxID",
			Handler:    _Ledger_QueryLedgerBlockByTxID_Handler,
		},
		{
			MethodName: "QueryLedgerInfoSpec",
			Handler:    _Ledger_QueryLedgerInfoSpec_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByHeightSpec",
			Handler:    _Ledger_QueryLedgerBlockByHeightSpec_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByHashSpec",
			Handler:    _Ledger_QueryLedgerBlockByHashSpec_Handler,
		},
		{
			MethodName: "QueryLedgerBlockByTxIDSpec",
			Handler:    _Ledger_QueryLedgerBlockByTxIDSpec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/chain/server.proto",
}

// LedgerConfigClient is the client API for LedgerConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerConfigClient interface {
	GetConfig(ctx context.Context, in *String, opts ...grpc.CallOption) (*Config, error)
	InitClient(ctx context.Context, in *ReqClient, opts ...grpc.CallOption) (*String, error)
	InitClientSelf(ctx context.Context, in *ReqClientSelf, opts ...grpc.CallOption) (*String, error)
	InitClientCustom(ctx context.Context, in *ReqClientCustom, opts ...grpc.CallOption) (*String, error)
	AddOrSetPeerForChannel(ctx context.Context, in *ReqChannelPeer, opts ...grpc.CallOption) (*String, error)
	AddOrSetQueryChannelPolicyForChannel(ctx context.Context, in *ReqChannelPolicyQuery, opts ...grpc.CallOption) (*String, error)
	AddOrSetDiscoveryPolicyForChannel(ctx context.Context, in *ReqChannelPolicyDiscovery, opts ...grpc.CallOption) (*String, error)
	AddOrSetEventServicePolicyForChannel(ctx context.Context, in *ReqChannelPolicyEvent, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrdererForOrganizations(ctx context.Context, in *ReqOrganizationsOrder, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrdererForOrganizationsSelf(ctx context.Context, in *ReqOrganizationsOrderSelf, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrgForOrganizations(ctx context.Context, in *ReqOrganizationsOrg, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrgForOrganizationsSelf(ctx context.Context, in *ReqOrganizationsOrgSelf, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrderer(ctx context.Context, in *ReqOrder, opts ...grpc.CallOption) (*String, error)
	AddOrSetOrdererSelf(ctx context.Context, in *ReqOrderSelf, opts ...grpc.CallOption) (*String, error)
	AddOrSetPeer(ctx context.Context, in *ReqPeer, opts ...grpc.CallOption) (*String, error)
	AddOrSetPeerSelf(ctx context.Context, in *ReqPeerSelf, opts ...grpc.CallOption) (*String, error)
	AddOrSetCertificateAuthority(ctx context.Context, in *ReqCertificateAuthority, opts ...grpc.CallOption) (*String, error)
	AddOrSetCertificateAuthoritySelf(ctx context.Context, in *ReqCertificateAuthoritySelf, opts ...grpc.CallOption) (*String, error)
}

type ledgerConfigClient struct {
	cc *grpc.ClientConn
}

func NewLedgerConfigClient(cc *grpc.ClientConn) LedgerConfigClient {
	return &ledgerConfigClient{cc}
}

func (c *ledgerConfigClient) GetConfig(ctx context.Context, in *String, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) InitClient(ctx context.Context, in *ReqClient, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/InitClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) InitClientSelf(ctx context.Context, in *ReqClientSelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/InitClientSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) InitClientCustom(ctx context.Context, in *ReqClientCustom, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/InitClientCustom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetPeerForChannel(ctx context.Context, in *ReqChannelPeer, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetPeerForChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetQueryChannelPolicyForChannel(ctx context.Context, in *ReqChannelPolicyQuery, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetQueryChannelPolicyForChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetDiscoveryPolicyForChannel(ctx context.Context, in *ReqChannelPolicyDiscovery, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetDiscoveryPolicyForChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetEventServicePolicyForChannel(ctx context.Context, in *ReqChannelPolicyEvent, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetEventServicePolicyForChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrdererForOrganizations(ctx context.Context, in *ReqOrganizationsOrder, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrdererForOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrdererForOrganizationsSelf(ctx context.Context, in *ReqOrganizationsOrderSelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrdererForOrganizationsSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrgForOrganizations(ctx context.Context, in *ReqOrganizationsOrg, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrgForOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrgForOrganizationsSelf(ctx context.Context, in *ReqOrganizationsOrgSelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrgForOrganizationsSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrderer(ctx context.Context, in *ReqOrder, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrderer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetOrdererSelf(ctx context.Context, in *ReqOrderSelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetOrdererSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetPeer(ctx context.Context, in *ReqPeer, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetPeerSelf(ctx context.Context, in *ReqPeerSelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetPeerSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetCertificateAuthority(ctx context.Context, in *ReqCertificateAuthority, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetCertificateAuthority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerConfigClient) AddOrSetCertificateAuthoritySelf(ctx context.Context, in *ReqCertificateAuthoritySelf, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/chain.LedgerConfig/AddOrSetCertificateAuthoritySelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerConfigServer is the server API for LedgerConfig service.
type LedgerConfigServer interface {
	GetConfig(context.Context, *String) (*Config, error)
	InitClient(context.Context, *ReqClient) (*String, error)
	InitClientSelf(context.Context, *ReqClientSelf) (*String, error)
	InitClientCustom(context.Context, *ReqClientCustom) (*String, error)
	AddOrSetPeerForChannel(context.Context, *ReqChannelPeer) (*String, error)
	AddOrSetQueryChannelPolicyForChannel(context.Context, *ReqChannelPolicyQuery) (*String, error)
	AddOrSetDiscoveryPolicyForChannel(context.Context, *ReqChannelPolicyDiscovery) (*String, error)
	AddOrSetEventServicePolicyForChannel(context.Context, *ReqChannelPolicyEvent) (*String, error)
	AddOrSetOrdererForOrganizations(context.Context, *ReqOrganizationsOrder) (*String, error)
	AddOrSetOrdererForOrganizationsSelf(context.Context, *ReqOrganizationsOrderSelf) (*String, error)
	AddOrSetOrgForOrganizations(context.Context, *ReqOrganizationsOrg) (*String, error)
	AddOrSetOrgForOrganizationsSelf(context.Context, *ReqOrganizationsOrgSelf) (*String, error)
	AddOrSetOrderer(context.Context, *ReqOrder) (*String, error)
	AddOrSetOrdererSelf(context.Context, *ReqOrderSelf) (*String, error)
	AddOrSetPeer(context.Context, *ReqPeer) (*String, error)
	AddOrSetPeerSelf(context.Context, *ReqPeerSelf) (*String, error)
	AddOrSetCertificateAuthority(context.Context, *ReqCertificateAuthority) (*String, error)
	AddOrSetCertificateAuthoritySelf(context.Context, *ReqCertificateAuthoritySelf) (*String, error)
}

func RegisterLedgerConfigServer(s *grpc.Server, srv LedgerConfigServer) {
	s.RegisterService(&_LedgerConfig_serviceDesc, srv)
}

func _LedgerConfig_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).GetConfig(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_InitClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).InitClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/InitClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).InitClient(ctx, req.(*ReqClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_InitClientSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqClientSelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).InitClientSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/InitClientSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).InitClientSelf(ctx, req.(*ReqClientSelf))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_InitClientCustom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqClientCustom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).InitClientCustom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/InitClientCustom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).InitClientCustom(ctx, req.(*ReqClientCustom))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetPeerForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqChannelPeer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetPeerForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetPeerForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetPeerForChannel(ctx, req.(*ReqChannelPeer))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetQueryChannelPolicyForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqChannelPolicyQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetQueryChannelPolicyForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetQueryChannelPolicyForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetQueryChannelPolicyForChannel(ctx, req.(*ReqChannelPolicyQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetDiscoveryPolicyForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqChannelPolicyDiscovery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetDiscoveryPolicyForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetDiscoveryPolicyForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetDiscoveryPolicyForChannel(ctx, req.(*ReqChannelPolicyDiscovery))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetEventServicePolicyForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqChannelPolicyEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetEventServicePolicyForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetEventServicePolicyForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetEventServicePolicyForChannel(ctx, req.(*ReqChannelPolicyEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrdererForOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrganizationsOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrdererForOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrdererForOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrdererForOrganizations(ctx, req.(*ReqOrganizationsOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrdererForOrganizationsSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrganizationsOrderSelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrdererForOrganizationsSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrdererForOrganizationsSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrdererForOrganizationsSelf(ctx, req.(*ReqOrganizationsOrderSelf))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrgForOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrganizationsOrg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrgForOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrgForOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrgForOrganizations(ctx, req.(*ReqOrganizationsOrg))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrgForOrganizationsSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrganizationsOrgSelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrgForOrganizationsSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrgForOrganizationsSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrgForOrganizationsSelf(ctx, req.(*ReqOrganizationsOrgSelf))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrderer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrderer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrderer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrderer(ctx, req.(*ReqOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetOrdererSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrderSelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetOrdererSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetOrdererSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetOrdererSelf(ctx, req.(*ReqOrderSelf))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPeer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetPeer(ctx, req.(*ReqPeer))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetPeerSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPeerSelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetPeerSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetPeerSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetPeerSelf(ctx, req.(*ReqPeerSelf))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetCertificateAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCertificateAuthority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetCertificateAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetCertificateAuthority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetCertificateAuthority(ctx, req.(*ReqCertificateAuthority))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerConfig_AddOrSetCertificateAuthoritySelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCertificateAuthoritySelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerConfigServer).AddOrSetCertificateAuthoritySelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.LedgerConfig/AddOrSetCertificateAuthoritySelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerConfigServer).AddOrSetCertificateAuthoritySelf(ctx, req.(*ReqCertificateAuthoritySelf))
	}
	return interceptor(ctx, in, info, handler)
}

var _LedgerConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.LedgerConfig",
	HandlerType: (*LedgerConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _LedgerConfig_GetConfig_Handler,
		},
		{
			MethodName: "InitClient",
			Handler:    _LedgerConfig_InitClient_Handler,
		},
		{
			MethodName: "InitClientSelf",
			Handler:    _LedgerConfig_InitClientSelf_Handler,
		},
		{
			MethodName: "InitClientCustom",
			Handler:    _LedgerConfig_InitClientCustom_Handler,
		},
		{
			MethodName: "AddOrSetPeerForChannel",
			Handler:    _LedgerConfig_AddOrSetPeerForChannel_Handler,
		},
		{
			MethodName: "AddOrSetQueryChannelPolicyForChannel",
			Handler:    _LedgerConfig_AddOrSetQueryChannelPolicyForChannel_Handler,
		},
		{
			MethodName: "AddOrSetDiscoveryPolicyForChannel",
			Handler:    _LedgerConfig_AddOrSetDiscoveryPolicyForChannel_Handler,
		},
		{
			MethodName: "AddOrSetEventServicePolicyForChannel",
			Handler:    _LedgerConfig_AddOrSetEventServicePolicyForChannel_Handler,
		},
		{
			MethodName: "AddOrSetOrdererForOrganizations",
			Handler:    _LedgerConfig_AddOrSetOrdererForOrganizations_Handler,
		},
		{
			MethodName: "AddOrSetOrdererForOrganizationsSelf",
			Handler:    _LedgerConfig_AddOrSetOrdererForOrganizationsSelf_Handler,
		},
		{
			MethodName: "AddOrSetOrgForOrganizations",
			Handler:    _LedgerConfig_AddOrSetOrgForOrganizations_Handler,
		},
		{
			MethodName: "AddOrSetOrgForOrganizationsSelf",
			Handler:    _LedgerConfig_AddOrSetOrgForOrganizationsSelf_Handler,
		},
		{
			MethodName: "AddOrSetOrderer",
			Handler:    _LedgerConfig_AddOrSetOrderer_Handler,
		},
		{
			MethodName: "AddOrSetOrdererSelf",
			Handler:    _LedgerConfig_AddOrSetOrdererSelf_Handler,
		},
		{
			MethodName: "AddOrSetPeer",
			Handler:    _LedgerConfig_AddOrSetPeer_Handler,
		},
		{
			MethodName: "AddOrSetPeerSelf",
			Handler:    _LedgerConfig_AddOrSetPeerSelf_Handler,
		},
		{
			MethodName: "AddOrSetCertificateAuthority",
			Handler:    _LedgerConfig_AddOrSetCertificateAuthority_Handler,
		},
		{
			MethodName: "AddOrSetCertificateAuthoritySelf",
			Handler:    _LedgerConfig_AddOrSetCertificateAuthoritySelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/chain/server.proto",
}
