// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/generate/cert.proto

package generate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqKeyConfig struct {
	CryptoType CryptoType `protobuf:"varint,1,opt,name=cryptoType,proto3,enum=generate.CryptoType" json:"cryptoType,omitempty"`
	// Types that are valid to be assigned to Algorithm:
	//	*ReqKeyConfig_EccAlgorithm
	//	*ReqKeyConfig_RsaAlgorithm
	Algorithm            isReqKeyConfig_Algorithm `protobuf_oneof:"Algorithm"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ReqKeyConfig) Reset()         { *m = ReqKeyConfig{} }
func (m *ReqKeyConfig) String() string { return proto.CompactTextString(m) }
func (*ReqKeyConfig) ProtoMessage()    {}
func (*ReqKeyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{0}
}

func (m *ReqKeyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqKeyConfig.Unmarshal(m, b)
}
func (m *ReqKeyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqKeyConfig.Marshal(b, m, deterministic)
}
func (m *ReqKeyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqKeyConfig.Merge(m, src)
}
func (m *ReqKeyConfig) XXX_Size() int {
	return xxx_messageInfo_ReqKeyConfig.Size(m)
}
func (m *ReqKeyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqKeyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ReqKeyConfig proto.InternalMessageInfo

func (m *ReqKeyConfig) GetCryptoType() CryptoType {
	if m != nil {
		return m.CryptoType
	}
	return CryptoType_ECDSA
}

type isReqKeyConfig_Algorithm interface {
	isReqKeyConfig_Algorithm()
}

type ReqKeyConfig_EccAlgorithm struct {
	EccAlgorithm EccAlgorithm `protobuf:"varint,2,opt,name=eccAlgorithm,proto3,enum=generate.EccAlgorithm,oneof"`
}

type ReqKeyConfig_RsaAlgorithm struct {
	RsaAlgorithm RsaAlgorithm `protobuf:"varint,3,opt,name=rsaAlgorithm,proto3,enum=generate.RsaAlgorithm,oneof"`
}

func (*ReqKeyConfig_EccAlgorithm) isReqKeyConfig_Algorithm() {}

func (*ReqKeyConfig_RsaAlgorithm) isReqKeyConfig_Algorithm() {}

func (m *ReqKeyConfig) GetAlgorithm() isReqKeyConfig_Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *ReqKeyConfig) GetEccAlgorithm() EccAlgorithm {
	if x, ok := m.GetAlgorithm().(*ReqKeyConfig_EccAlgorithm); ok {
		return x.EccAlgorithm
	}
	return EccAlgorithm_p256
}

func (m *ReqKeyConfig) GetRsaAlgorithm() RsaAlgorithm {
	if x, ok := m.GetAlgorithm().(*ReqKeyConfig_RsaAlgorithm); ok {
		return x.RsaAlgorithm
	}
	return RsaAlgorithm_r2048
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReqKeyConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReqKeyConfig_OneofMarshaler, _ReqKeyConfig_OneofUnmarshaler, _ReqKeyConfig_OneofSizer, []interface{}{
		(*ReqKeyConfig_EccAlgorithm)(nil),
		(*ReqKeyConfig_RsaAlgorithm)(nil),
	}
}

func _ReqKeyConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReqKeyConfig)
	// Algorithm
	switch x := m.Algorithm.(type) {
	case *ReqKeyConfig_EccAlgorithm:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.EccAlgorithm))
	case *ReqKeyConfig_RsaAlgorithm:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.RsaAlgorithm))
	case nil:
	default:
		return fmt.Errorf("ReqKeyConfig.Algorithm has unexpected type %T", x)
	}
	return nil
}

func _ReqKeyConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReqKeyConfig)
	switch tag {
	case 2: // Algorithm.eccAlgorithm
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Algorithm = &ReqKeyConfig_EccAlgorithm{EccAlgorithm(x)}
		return true, err
	case 3: // Algorithm.rsaAlgorithm
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Algorithm = &ReqKeyConfig_RsaAlgorithm{RsaAlgorithm(x)}
		return true, err
	default:
		return false, nil
	}
}

func _ReqKeyConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReqKeyConfig)
	// Algorithm
	switch x := m.Algorithm.(type) {
	case *ReqKeyConfig_EccAlgorithm:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.EccAlgorithm))
	case *ReqKeyConfig_RsaAlgorithm:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.RsaAlgorithm))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RespKeyConfig struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	PriKeyFilePath       string   `protobuf:"bytes,3,opt,name=priKeyFilePath,proto3" json:"priKeyFilePath,omitempty"`
	PubKeyFilePath       string   `protobuf:"bytes,4,opt,name=pubKeyFilePath,proto3" json:"pubKeyFilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespKeyConfig) Reset()         { *m = RespKeyConfig{} }
func (m *RespKeyConfig) String() string { return proto.CompactTextString(m) }
func (*RespKeyConfig) ProtoMessage()    {}
func (*RespKeyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{1}
}

func (m *RespKeyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespKeyConfig.Unmarshal(m, b)
}
func (m *RespKeyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespKeyConfig.Marshal(b, m, deterministic)
}
func (m *RespKeyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespKeyConfig.Merge(m, src)
}
func (m *RespKeyConfig) XXX_Size() int {
	return xxx_messageInfo_RespKeyConfig.Size(m)
}
func (m *RespKeyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RespKeyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RespKeyConfig proto.InternalMessageInfo

func (m *RespKeyConfig) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespKeyConfig) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RespKeyConfig) GetPriKeyFilePath() string {
	if m != nil {
		return m.PriKeyFilePath
	}
	return ""
}

func (m *RespKeyConfig) GetPubKeyFilePath() string {
	if m != nil {
		return m.PubKeyFilePath
	}
	return ""
}

type ReqCreateLeague struct {
	Domain               string        `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PriData              []byte        `protobuf:"bytes,2,opt,name=priData,proto3" json:"priData,omitempty"`
	PriTlsData           []byte        `protobuf:"bytes,3,opt,name=priTlsData,proto3" json:"priTlsData,omitempty"`
	Csr                  *CSR          `protobuf:"bytes,4,opt,name=csr,proto3" json:"csr,omitempty"`
	SignAlgorithm        SignAlgorithm `protobuf:"varint,5,opt,name=signAlgorithm,proto3,enum=generate.SignAlgorithm" json:"signAlgorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqCreateLeague) Reset()         { *m = ReqCreateLeague{} }
func (m *ReqCreateLeague) String() string { return proto.CompactTextString(m) }
func (*ReqCreateLeague) ProtoMessage()    {}
func (*ReqCreateLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{2}
}

func (m *ReqCreateLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateLeague.Unmarshal(m, b)
}
func (m *ReqCreateLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateLeague.Marshal(b, m, deterministic)
}
func (m *ReqCreateLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateLeague.Merge(m, src)
}
func (m *ReqCreateLeague) XXX_Size() int {
	return xxx_messageInfo_ReqCreateLeague.Size(m)
}
func (m *ReqCreateLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateLeague proto.InternalMessageInfo

func (m *ReqCreateLeague) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ReqCreateLeague) GetPriData() []byte {
	if m != nil {
		return m.PriData
	}
	return nil
}

func (m *ReqCreateLeague) GetPriTlsData() []byte {
	if m != nil {
		return m.PriTlsData
	}
	return nil
}

func (m *ReqCreateLeague) GetCsr() *CSR {
	if m != nil {
		return m.Csr
	}
	return nil
}

func (m *ReqCreateLeague) GetSignAlgorithm() SignAlgorithm {
	if m != nil {
		return m.SignAlgorithm
	}
	return SignAlgorithm_SHA256WithRSA
}

type RespCreateLeague struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateLeague) Reset()         { *m = RespCreateLeague{} }
func (m *RespCreateLeague) String() string { return proto.CompactTextString(m) }
func (*RespCreateLeague) ProtoMessage()    {}
func (*RespCreateLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{3}
}

func (m *RespCreateLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateLeague.Unmarshal(m, b)
}
func (m *RespCreateLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateLeague.Marshal(b, m, deterministic)
}
func (m *RespCreateLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateLeague.Merge(m, src)
}
func (m *RespCreateLeague) XXX_Size() int {
	return xxx_messageInfo_RespCreateLeague.Size(m)
}
func (m *RespCreateLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateLeague.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateLeague proto.InternalMessageInfo

func (m *RespCreateLeague) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespCreateLeague) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ReqCreateOrg struct {
	OrgType              OrgType  `protobuf:"varint,1,opt,name=orgType,proto3,enum=generate.OrgType" json:"orgType,omitempty"`
	LeagueDomain         string   `protobuf:"bytes,2,opt,name=leagueDomain,proto3" json:"leagueDomain,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Domain               string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateOrg) Reset()         { *m = ReqCreateOrg{} }
func (m *ReqCreateOrg) String() string { return proto.CompactTextString(m) }
func (*ReqCreateOrg) ProtoMessage()    {}
func (*ReqCreateOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{4}
}

func (m *ReqCreateOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateOrg.Unmarshal(m, b)
}
func (m *ReqCreateOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateOrg.Marshal(b, m, deterministic)
}
func (m *ReqCreateOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateOrg.Merge(m, src)
}
func (m *ReqCreateOrg) XXX_Size() int {
	return xxx_messageInfo_ReqCreateOrg.Size(m)
}
func (m *ReqCreateOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateOrg.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateOrg proto.InternalMessageInfo

func (m *ReqCreateOrg) GetOrgType() OrgType {
	if m != nil {
		return m.OrgType
	}
	return OrgType_Order
}

func (m *ReqCreateOrg) GetLeagueDomain() string {
	if m != nil {
		return m.LeagueDomain
	}
	return ""
}

func (m *ReqCreateOrg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateOrg) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type RespCreateOrg struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateOrg) Reset()         { *m = RespCreateOrg{} }
func (m *RespCreateOrg) String() string { return proto.CompactTextString(m) }
func (*RespCreateOrg) ProtoMessage()    {}
func (*RespCreateOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{5}
}

func (m *RespCreateOrg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateOrg.Unmarshal(m, b)
}
func (m *RespCreateOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateOrg.Marshal(b, m, deterministic)
}
func (m *RespCreateOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateOrg.Merge(m, src)
}
func (m *RespCreateOrg) XXX_Size() int {
	return xxx_messageInfo_RespCreateOrg.Size(m)
}
func (m *RespCreateOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateOrg.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateOrg proto.InternalMessageInfo

func (m *RespCreateOrg) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespCreateOrg) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ReqCreateCsr struct {
	LeagueDomain         string        `protobuf:"bytes,2,opt,name=leagueDomain,proto3" json:"leagueDomain,omitempty"`
	OrgName              string        `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgDomain            string        `protobuf:"bytes,4,opt,name=orgDomain,proto3" json:"orgDomain,omitempty"`
	PriKey               []byte        `protobuf:"bytes,5,opt,name=priKey,proto3" json:"priKey,omitempty"`
	Name                 *CSR          `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	SignAlgorithm        SignAlgorithm `protobuf:"varint,7,opt,name=signAlgorithm,proto3,enum=generate.SignAlgorithm" json:"signAlgorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqCreateCsr) Reset()         { *m = ReqCreateCsr{} }
func (m *ReqCreateCsr) String() string { return proto.CompactTextString(m) }
func (*ReqCreateCsr) ProtoMessage()    {}
func (*ReqCreateCsr) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{6}
}

func (m *ReqCreateCsr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateCsr.Unmarshal(m, b)
}
func (m *ReqCreateCsr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateCsr.Marshal(b, m, deterministic)
}
func (m *ReqCreateCsr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateCsr.Merge(m, src)
}
func (m *ReqCreateCsr) XXX_Size() int {
	return xxx_messageInfo_ReqCreateCsr.Size(m)
}
func (m *ReqCreateCsr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateCsr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateCsr proto.InternalMessageInfo

func (m *ReqCreateCsr) GetLeagueDomain() string {
	if m != nil {
		return m.LeagueDomain
	}
	return ""
}

func (m *ReqCreateCsr) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *ReqCreateCsr) GetOrgDomain() string {
	if m != nil {
		return m.OrgDomain
	}
	return ""
}

func (m *ReqCreateCsr) GetPriKey() []byte {
	if m != nil {
		return m.PriKey
	}
	return nil
}

func (m *ReqCreateCsr) GetName() *CSR {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ReqCreateCsr) GetSignAlgorithm() SignAlgorithm {
	if m != nil {
		return m.SignAlgorithm
	}
	return SignAlgorithm_SHA256WithRSA
}

type RespCreateCsr struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateCsr) Reset()         { *m = RespCreateCsr{} }
func (m *RespCreateCsr) String() string { return proto.CompactTextString(m) }
func (*RespCreateCsr) ProtoMessage()    {}
func (*RespCreateCsr) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{7}
}

func (m *RespCreateCsr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateCsr.Unmarshal(m, b)
}
func (m *RespCreateCsr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateCsr.Marshal(b, m, deterministic)
}
func (m *RespCreateCsr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateCsr.Merge(m, src)
}
func (m *RespCreateCsr) XXX_Size() int {
	return xxx_messageInfo_RespCreateCsr.Size(m)
}
func (m *RespCreateCsr) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateCsr.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateCsr proto.InternalMessageInfo

func (m *RespCreateCsr) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespCreateCsr) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ReqCreateOrgNode struct {
	OrgType              OrgType   `protobuf:"varint,1,opt,name=orgType,proto3,enum=generate.OrgType" json:"orgType,omitempty"`
	OrgChild             *OrgChild `protobuf:"bytes,2,opt,name=orgChild,proto3" json:"orgChild,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqCreateOrgNode) Reset()         { *m = ReqCreateOrgNode{} }
func (m *ReqCreateOrgNode) String() string { return proto.CompactTextString(m) }
func (*ReqCreateOrgNode) ProtoMessage()    {}
func (*ReqCreateOrgNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{8}
}

func (m *ReqCreateOrgNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateOrgNode.Unmarshal(m, b)
}
func (m *ReqCreateOrgNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateOrgNode.Marshal(b, m, deterministic)
}
func (m *ReqCreateOrgNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateOrgNode.Merge(m, src)
}
func (m *ReqCreateOrgNode) XXX_Size() int {
	return xxx_messageInfo_ReqCreateOrgNode.Size(m)
}
func (m *ReqCreateOrgNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateOrgNode.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateOrgNode proto.InternalMessageInfo

func (m *ReqCreateOrgNode) GetOrgType() OrgType {
	if m != nil {
		return m.OrgType
	}
	return OrgType_Order
}

func (m *ReqCreateOrgNode) GetOrgChild() *OrgChild {
	if m != nil {
		return m.OrgChild
	}
	return nil
}

type RespCreateOrgNode struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateOrgNode) Reset()         { *m = RespCreateOrgNode{} }
func (m *RespCreateOrgNode) String() string { return proto.CompactTextString(m) }
func (*RespCreateOrgNode) ProtoMessage()    {}
func (*RespCreateOrgNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{9}
}

func (m *RespCreateOrgNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateOrgNode.Unmarshal(m, b)
}
func (m *RespCreateOrgNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateOrgNode.Marshal(b, m, deterministic)
}
func (m *RespCreateOrgNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateOrgNode.Merge(m, src)
}
func (m *RespCreateOrgNode) XXX_Size() int {
	return xxx_messageInfo_RespCreateOrgNode.Size(m)
}
func (m *RespCreateOrgNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateOrgNode.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateOrgNode proto.InternalMessageInfo

func (m *RespCreateOrgNode) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespCreateOrgNode) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ReqCreateOrgUser struct {
	OrgType              OrgType   `protobuf:"varint,1,opt,name=orgType,proto3,enum=generate.OrgType" json:"orgType,omitempty"`
	OrgChild             *OrgChild `protobuf:"bytes,2,opt,name=orgChild,proto3" json:"orgChild,omitempty"`
	IsAdmin              bool      `protobuf:"varint,3,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqCreateOrgUser) Reset()         { *m = ReqCreateOrgUser{} }
func (m *ReqCreateOrgUser) String() string { return proto.CompactTextString(m) }
func (*ReqCreateOrgUser) ProtoMessage()    {}
func (*ReqCreateOrgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{10}
}

func (m *ReqCreateOrgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateOrgUser.Unmarshal(m, b)
}
func (m *ReqCreateOrgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateOrgUser.Marshal(b, m, deterministic)
}
func (m *ReqCreateOrgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateOrgUser.Merge(m, src)
}
func (m *ReqCreateOrgUser) XXX_Size() int {
	return xxx_messageInfo_ReqCreateOrgUser.Size(m)
}
func (m *ReqCreateOrgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateOrgUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateOrgUser proto.InternalMessageInfo

func (m *ReqCreateOrgUser) GetOrgType() OrgType {
	if m != nil {
		return m.OrgType
	}
	return OrgType_Order
}

func (m *ReqCreateOrgUser) GetOrgChild() *OrgChild {
	if m != nil {
		return m.OrgChild
	}
	return nil
}

func (m *ReqCreateOrgUser) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type RespCreateOrgUser struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=generate.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateOrgUser) Reset()         { *m = RespCreateOrgUser{} }
func (m *RespCreateOrgUser) String() string { return proto.CompactTextString(m) }
func (*RespCreateOrgUser) ProtoMessage()    {}
func (*RespCreateOrgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{11}
}

func (m *RespCreateOrgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateOrgUser.Unmarshal(m, b)
}
func (m *RespCreateOrgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateOrgUser.Marshal(b, m, deterministic)
}
func (m *RespCreateOrgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateOrgUser.Merge(m, src)
}
func (m *RespCreateOrgUser) XXX_Size() int {
	return xxx_messageInfo_RespCreateOrgUser.Size(m)
}
func (m *RespCreateOrgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateOrgUser.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateOrgUser proto.InternalMessageInfo

func (m *RespCreateOrgUser) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespCreateOrgUser) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type OrgChild struct {
	LeagueDomain         string        `protobuf:"bytes,2,opt,name=leagueDomain,proto3" json:"leagueDomain,omitempty"`
	OrgName              string        `protobuf:"bytes,3,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgDomain            string        `protobuf:"bytes,4,opt,name=orgDomain,proto3" json:"orgDomain,omitempty"`
	Name                 string        `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PubTlsData           []byte        `protobuf:"bytes,7,opt,name=pubTlsData,proto3" json:"pubTlsData,omitempty"`
	SignAlgorithm        SignAlgorithm `protobuf:"varint,8,opt,name=signAlgorithm,proto3,enum=generate.SignAlgorithm" json:"signAlgorithm,omitempty"`
	EnrollInfo           *EnrollInfo   `protobuf:"bytes,9,opt,name=enrollInfo,proto3" json:"enrollInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrgChild) Reset()         { *m = OrgChild{} }
func (m *OrgChild) String() string { return proto.CompactTextString(m) }
func (*OrgChild) ProtoMessage()    {}
func (*OrgChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{12}
}

func (m *OrgChild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgChild.Unmarshal(m, b)
}
func (m *OrgChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgChild.Marshal(b, m, deterministic)
}
func (m *OrgChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgChild.Merge(m, src)
}
func (m *OrgChild) XXX_Size() int {
	return xxx_messageInfo_OrgChild.Size(m)
}
func (m *OrgChild) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgChild.DiscardUnknown(m)
}

var xxx_messageInfo_OrgChild proto.InternalMessageInfo

func (m *OrgChild) GetLeagueDomain() string {
	if m != nil {
		return m.LeagueDomain
	}
	return ""
}

func (m *OrgChild) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *OrgChild) GetOrgDomain() string {
	if m != nil {
		return m.OrgDomain
	}
	return ""
}

func (m *OrgChild) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrgChild) GetPubTlsData() []byte {
	if m != nil {
		return m.PubTlsData
	}
	return nil
}

func (m *OrgChild) GetSignAlgorithm() SignAlgorithm {
	if m != nil {
		return m.SignAlgorithm
	}
	return SignAlgorithm_SHA256WithRSA
}

func (m *OrgChild) GetEnrollInfo() *EnrollInfo {
	if m != nil {
		return m.EnrollInfo
	}
	return nil
}

type EnrollInfo struct {
	CsrPem               []byte         `protobuf:"bytes,1,opt,name=csrPem,proto3" json:"csrPem,omitempty"`
	FabricCaServerURL    string         `protobuf:"bytes,2,opt,name=fabricCaServerURL,proto3" json:"fabricCaServerURL,omitempty"`
	NotBefore            int64          `protobuf:"varint,3,opt,name=notBefore,proto3" json:"notBefore,omitempty"`
	NotAfter             int64          `protobuf:"varint,4,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	EnrollRequest        *EnrollRequest `protobuf:"bytes,5,opt,name=enrollRequest,proto3" json:"enrollRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EnrollInfo) Reset()         { *m = EnrollInfo{} }
func (m *EnrollInfo) String() string { return proto.CompactTextString(m) }
func (*EnrollInfo) ProtoMessage()    {}
func (*EnrollInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{13}
}

func (m *EnrollInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollInfo.Unmarshal(m, b)
}
func (m *EnrollInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollInfo.Marshal(b, m, deterministic)
}
func (m *EnrollInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollInfo.Merge(m, src)
}
func (m *EnrollInfo) XXX_Size() int {
	return xxx_messageInfo_EnrollInfo.Size(m)
}
func (m *EnrollInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollInfo proto.InternalMessageInfo

func (m *EnrollInfo) GetCsrPem() []byte {
	if m != nil {
		return m.CsrPem
	}
	return nil
}

func (m *EnrollInfo) GetFabricCaServerURL() string {
	if m != nil {
		return m.FabricCaServerURL
	}
	return ""
}

func (m *EnrollInfo) GetNotBefore() int64 {
	if m != nil {
		return m.NotBefore
	}
	return 0
}

func (m *EnrollInfo) GetNotAfter() int64 {
	if m != nil {
		return m.NotAfter
	}
	return 0
}

func (m *EnrollInfo) GetEnrollRequest() *EnrollRequest {
	if m != nil {
		return m.EnrollRequest
	}
	return nil
}

type EnrollRequest struct {
	EnrollID             string             `protobuf:"bytes,1,opt,name=enrollID,proto3" json:"enrollID,omitempty"`
	Secret               string             `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Name                 *CSR               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Profile              string             `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Label                string             `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	CaName               string             `protobuf:"bytes,6,opt,name=caName,proto3" json:"caName,omitempty"`
	Hosts                []string           `protobuf:"bytes,7,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Attrs                []*EnrollAttribute `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EnrollRequest) Reset()         { *m = EnrollRequest{} }
func (m *EnrollRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollRequest) ProtoMessage()    {}
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{14}
}

func (m *EnrollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollRequest.Unmarshal(m, b)
}
func (m *EnrollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollRequest.Marshal(b, m, deterministic)
}
func (m *EnrollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollRequest.Merge(m, src)
}
func (m *EnrollRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollRequest.Size(m)
}
func (m *EnrollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollRequest proto.InternalMessageInfo

func (m *EnrollRequest) GetEnrollID() string {
	if m != nil {
		return m.EnrollID
	}
	return ""
}

func (m *EnrollRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *EnrollRequest) GetName() *CSR {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *EnrollRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *EnrollRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *EnrollRequest) GetCaName() string {
	if m != nil {
		return m.CaName
	}
	return ""
}

func (m *EnrollRequest) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *EnrollRequest) GetAttrs() []*EnrollAttribute {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type EnrollAttribute struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Optional             bool     `protobuf:"varint,2,opt,name=optional,proto3" json:"optional,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollAttribute) Reset()         { *m = EnrollAttribute{} }
func (m *EnrollAttribute) String() string { return proto.CompactTextString(m) }
func (*EnrollAttribute) ProtoMessage()    {}
func (*EnrollAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{15}
}

func (m *EnrollAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollAttribute.Unmarshal(m, b)
}
func (m *EnrollAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollAttribute.Marshal(b, m, deterministic)
}
func (m *EnrollAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollAttribute.Merge(m, src)
}
func (m *EnrollAttribute) XXX_Size() int {
	return xxx_messageInfo_EnrollAttribute.Size(m)
}
func (m *EnrollAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollAttribute proto.InternalMessageInfo

func (m *EnrollAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnrollAttribute) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

// csr 证书请求申请内容
type CSR struct {
	Country              []string `protobuf:"bytes,1,rep,name=country,proto3" json:"country,omitempty"`
	Organization         []string `protobuf:"bytes,2,rep,name=organization,proto3" json:"organization,omitempty"`
	OrganizationalUnit   []string `protobuf:"bytes,3,rep,name=organizationalUnit,proto3" json:"organizationalUnit,omitempty"`
	Locality             []string `protobuf:"bytes,4,rep,name=locality,proto3" json:"locality,omitempty"`
	Province             []string `protobuf:"bytes,5,rep,name=province,proto3" json:"province,omitempty"`
	StreetAddress        []string `protobuf:"bytes,6,rep,name=streetAddress,proto3" json:"streetAddress,omitempty"`
	PostalCode           []string `protobuf:"bytes,7,rep,name=postalCode,proto3" json:"postalCode,omitempty"`
	SerialNumber         string   `protobuf:"bytes,8,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	CommonName           string   `protobuf:"bytes,9,opt,name=commonName,proto3" json:"commonName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSR) Reset()         { *m = CSR{} }
func (m *CSR) String() string { return proto.CompactTextString(m) }
func (*CSR) ProtoMessage()    {}
func (*CSR) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a6d3a83fb7b1ea9, []int{16}
}

func (m *CSR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSR.Unmarshal(m, b)
}
func (m *CSR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSR.Marshal(b, m, deterministic)
}
func (m *CSR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSR.Merge(m, src)
}
func (m *CSR) XXX_Size() int {
	return xxx_messageInfo_CSR.Size(m)
}
func (m *CSR) XXX_DiscardUnknown() {
	xxx_messageInfo_CSR.DiscardUnknown(m)
}

var xxx_messageInfo_CSR proto.InternalMessageInfo

func (m *CSR) GetCountry() []string {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *CSR) GetOrganization() []string {
	if m != nil {
		return m.Organization
	}
	return nil
}

func (m *CSR) GetOrganizationalUnit() []string {
	if m != nil {
		return m.OrganizationalUnit
	}
	return nil
}

func (m *CSR) GetLocality() []string {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *CSR) GetProvince() []string {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *CSR) GetStreetAddress() []string {
	if m != nil {
		return m.StreetAddress
	}
	return nil
}

func (m *CSR) GetPostalCode() []string {
	if m != nil {
		return m.PostalCode
	}
	return nil
}

func (m *CSR) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *CSR) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqKeyConfig)(nil), "generate.ReqKeyConfig")
	proto.RegisterType((*RespKeyConfig)(nil), "generate.RespKeyConfig")
	proto.RegisterType((*ReqCreateLeague)(nil), "generate.ReqCreateLeague")
	proto.RegisterType((*RespCreateLeague)(nil), "generate.RespCreateLeague")
	proto.RegisterType((*ReqCreateOrg)(nil), "generate.ReqCreateOrg")
	proto.RegisterType((*RespCreateOrg)(nil), "generate.RespCreateOrg")
	proto.RegisterType((*ReqCreateCsr)(nil), "generate.ReqCreateCsr")
	proto.RegisterType((*RespCreateCsr)(nil), "generate.RespCreateCsr")
	proto.RegisterType((*ReqCreateOrgNode)(nil), "generate.ReqCreateOrgNode")
	proto.RegisterType((*RespCreateOrgNode)(nil), "generate.RespCreateOrgNode")
	proto.RegisterType((*ReqCreateOrgUser)(nil), "generate.ReqCreateOrgUser")
	proto.RegisterType((*RespCreateOrgUser)(nil), "generate.RespCreateOrgUser")
	proto.RegisterType((*OrgChild)(nil), "generate.OrgChild")
	proto.RegisterType((*EnrollInfo)(nil), "generate.EnrollInfo")
	proto.RegisterType((*EnrollRequest)(nil), "generate.EnrollRequest")
	proto.RegisterType((*EnrollAttribute)(nil), "generate.EnrollAttribute")
	proto.RegisterType((*CSR)(nil), "generate.CSR")
}

func init() { proto.RegisterFile("grpc/proto/generate/cert.proto", fileDescriptor_4a6d3a83fb7b1ea9) }

var fileDescriptor_4a6d3a83fb7b1ea9 = []byte{
	// 992 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6e, 0x24, 0x35,
	0x14, 0xa5, 0x52, 0x79, 0x74, 0x39, 0x9d, 0x0c, 0x31, 0xa3, 0xa1, 0x88, 0xd0, 0x4c, 0x28, 0x21,
	0x34, 0xe2, 0xd1, 0x91, 0x02, 0x4b, 0x58, 0x74, 0x3a, 0x41, 0xa0, 0x84, 0x4e, 0xe4, 0x4c, 0x36,
	0xec, 0xdc, 0xd5, 0xb7, 0x2b, 0x96, 0xaa, 0xed, 0x8a, 0xed, 0x1e, 0xa9, 0xf9, 0x03, 0xc4, 0x82,
	0x0f, 0xe0, 0x3b, 0xf8, 0x02, 0x96, 0x88, 0xbf, 0xe0, 0x17, 0xd8, 0x23, 0xdf, 0x7a, 0xb9, 0x92,
	0x46, 0x22, 0x13, 0xcd, 0xae, 0xcf, 0x3d, 0xc7, 0xd5, 0xf7, 0x1c, 0x5f, 0xbb, 0x8a, 0x3c, 0xcf,
	0x74, 0x91, 0x1e, 0x16, 0x5a, 0x59, 0x75, 0x98, 0x81, 0x04, 0xcd, 0x2d, 0x1c, 0xa6, 0xa0, 0xed,
	0x00, 0x6b, 0xb4, 0x57, 0x17, 0xf7, 0x0f, 0x56, 0x29, 0x35, 0x98, 0x45, 0x5e, 0x69, 0xf7, 0x5f,
	0xac, 0x52, 0x80, 0x5c, 0xcc, 0x4d, 0x29, 0x48, 0xfe, 0x0a, 0x48, 0x9f, 0xc1, 0xed, 0x19, 0x2c,
	0x47, 0x4a, 0xce, 0x44, 0x46, 0xbf, 0x22, 0x24, 0xd5, 0xcb, 0xc2, 0xaa, 0x57, 0xcb, 0x02, 0xe2,
	0xe0, 0x20, 0x78, 0xb9, 0x7b, 0xf4, 0x74, 0x50, 0xaf, 0x1d, 0x8c, 0x1a, 0x8e, 0x79, 0x3a, 0xfa,
	0x35, 0xe9, 0x43, 0x9a, 0x0e, 0xf3, 0x4c, 0x69, 0x61, 0x6f, 0xe6, 0xf1, 0x1a, 0xae, 0x7b, 0xd6,
	0xae, 0x3b, 0xf5, 0xd8, 0xef, 0xde, 0x61, 0x1d, 0xb5, 0x5b, 0xad, 0x0d, 0x6f, 0x57, 0x87, 0x77,
	0x57, 0x33, 0x8f, 0x75, 0xab, 0x7d, 0xf5, 0xf1, 0x36, 0x89, 0x1a, 0x90, 0xfc, 0x16, 0x90, 0x1d,
	0x06, 0xa6, 0x68, 0x0d, 0x25, 0x64, 0x3d, 0x55, 0xd3, 0xda, 0xca, 0xae, 0x67, 0x45, 0x4d, 0x81,
	0x21, 0x47, 0x9f, 0x91, 0x4d, 0xd0, 0xfa, 0x07, 0x93, 0x61, 0xe3, 0x11, 0xab, 0x10, 0xfd, 0x84,
	0xec, 0x16, 0x5a, 0x9c, 0xc1, 0xf2, 0x5b, 0x91, 0xc3, 0x25, 0xb7, 0x37, 0xd8, 0x5a, 0xc4, 0xee,
	0x54, 0x51, 0xb7, 0x98, 0xf8, 0xba, 0xf5, 0x4a, 0xd7, 0xa9, 0x26, 0x7f, 0x04, 0xe4, 0x09, 0x83,
	0xdb, 0x91, 0x06, 0x6e, 0xe1, 0x1c, 0x78, 0xb6, 0xc0, 0xff, 0x9e, 0xaa, 0x39, 0x17, 0x12, 0x3b,
	0x8c, 0x58, 0x85, 0x68, 0x4c, 0xb6, 0x0a, 0x2d, 0x4e, 0xb8, 0xe5, 0xd8, 0x54, 0x9f, 0xd5, 0x90,
	0x3e, 0x27, 0xa4, 0xd0, 0xe2, 0x55, 0x6e, 0x90, 0x0c, 0x91, 0xf4, 0x2a, 0xf4, 0x05, 0x09, 0x53,
	0xa3, 0xb1, 0x85, 0xed, 0xa3, 0x1d, 0xcf, 0xf0, 0x15, 0x63, 0x8e, 0xa1, 0xdf, 0x90, 0x1d, 0x23,
	0x32, 0xd9, 0x06, 0xbe, 0x81, 0xd9, 0xbc, 0xdf, 0x4a, 0xaf, 0x7c, 0x9a, 0x75, 0xd5, 0xc9, 0x98,
	0xbc, 0xeb, 0x22, 0xee, 0xb8, 0x78, 0x44, 0xca, 0xc9, 0x2f, 0xe5, 0x0c, 0x96, 0xcf, 0xbb, 0xd0,
	0x19, 0xfd, 0x8c, 0x6c, 0x29, 0x9d, 0x79, 0x03, 0xb8, 0xd7, 0x3e, 0xef, 0xa2, 0x24, 0x58, 0xad,
	0xa0, 0x09, 0xe9, 0xe7, 0xd8, 0xc3, 0x49, 0x99, 0x62, 0xf9, 0xec, 0x4e, 0x8d, 0x52, 0xb2, 0x2e,
	0xf9, 0x1c, 0xaa, 0xdd, 0xc3, 0xdf, 0x5e, 0xee, 0xeb, 0x7e, 0xee, 0xc9, 0x59, 0x39, 0x40, 0x6d,
	0x37, 0x8f, 0xb1, 0xf6, 0xb7, 0x6f, 0x6d, 0x64, 0xf4, 0xff, 0xea, 0x36, 0x46, 0xfb, 0xe3, 0xb6,
	0xe1, 0x1a, 0xd2, 0x0f, 0x49, 0xa4, 0x74, 0x76, 0xe2, 0xb7, 0xdd, 0x16, 0x5c, 0x13, 0xe5, 0x5c,
	0xe2, 0x7e, 0xf6, 0x59, 0x85, 0xe8, 0x47, 0x95, 0xfb, 0xcd, 0x55, 0x03, 0x51, 0x86, 0x71, 0x6f,
	0x22, 0xb6, 0x1e, 0x34, 0x11, 0x9d, 0xcc, 0x4a, 0x9b, 0x6f, 0x9e, 0x99, 0x72, 0xe3, 0xd5, 0x4e,
	0xc3, 0xd8, 0x69, 0x1f, 0x34, 0x11, 0x03, 0xd2, 0x53, 0x3a, 0x1b, 0xdd, 0x88, 0x7c, 0x8a, 0x8f,
	0xde, 0x3e, 0xa2, 0x1d, 0x35, 0x32, 0xac, 0xd1, 0x24, 0x17, 0x64, 0xaf, 0xb3, 0xe3, 0xf8, 0x8f,
	0x8f, 0x71, 0xf0, 0x73, 0xd0, 0xb5, 0x70, 0x6d, 0x40, 0xbf, 0x55, 0x0b, 0x6e, 0x64, 0x84, 0x19,
	0x4e, 0xe7, 0x42, 0xe2, 0xc8, 0xf4, 0x58, 0x0d, 0xef, 0x99, 0xc3, 0x5e, 0x1e, 0x63, 0xee, 0xd7,
	0x35, 0xd2, 0xab, 0x3b, 0x78, 0xab, 0xe3, 0x5c, 0x1f, 0xda, 0x0d, 0xef, 0xd0, 0xba, 0xab, 0x6f,
	0x31, 0xa9, 0xaf, 0xbe, 0xad, 0xea, 0xea, 0x6b, 0x2a, 0xf7, 0xe7, 0xb8, 0xf7, 0x90, 0x39, 0x76,
	0x2f, 0x3f, 0x90, 0x5a, 0xe5, 0xf9, 0xf7, 0x72, 0xa6, 0xe2, 0x08, 0x83, 0xf7, 0x5e, 0x7e, 0xa7,
	0x0d, 0xc7, 0x3c, 0x5d, 0xf2, 0x67, 0x40, 0x48, 0x4b, 0xb9, 0xe0, 0x52, 0xa3, 0x2f, 0x61, 0x8e,
	0xf1, 0xf6, 0x59, 0x85, 0xe8, 0xe7, 0x64, 0x6f, 0xc6, 0x27, 0x5a, 0xa4, 0x23, 0x7e, 0x05, 0xfa,
	0x35, 0xe8, 0x6b, 0x76, 0x5e, 0x05, 0x76, 0x9f, 0x70, 0xd9, 0x48, 0x65, 0x8f, 0x61, 0xa6, 0x74,
	0x99, 0x5b, 0xc8, 0xda, 0x02, 0xdd, 0x27, 0x3d, 0xa9, 0xec, 0x70, 0x66, 0xa1, 0xbc, 0xe7, 0x43,
	0xd6, 0x60, 0x97, 0x41, 0xd9, 0x1c, 0x83, 0xdb, 0x05, 0x18, 0x8b, 0x01, 0x6e, 0xfb, 0x19, 0x9c,
	0xfa, 0x34, 0xeb, 0xaa, 0x93, 0x7f, 0x02, 0xb2, 0xd3, 0x11, 0xb8, 0x3f, 0xab, 0xdc, 0x9e, 0x54,
	0xef, 0xa8, 0x06, 0x3b, 0xb3, 0x06, 0x52, 0x0d, 0xb6, 0x9e, 0x92, 0x12, 0x35, 0x77, 0x4e, 0xf8,
	0xdf, 0x77, 0x0e, 0xbe, 0xe0, 0xd4, 0x4c, 0xe4, 0x50, 0xed, 0x7d, 0x0d, 0xe9, 0x53, 0xb2, 0x91,
	0xf3, 0x09, 0xe4, 0xd5, 0xd6, 0x97, 0x00, 0x73, 0xe5, 0xe3, 0xfa, 0x22, 0x8b, 0x58, 0x85, 0x9c,
	0xfa, 0x46, 0x19, 0x6b, 0xe2, 0xad, 0x83, 0xd0, 0xa9, 0x11, 0xd0, 0x43, 0xb2, 0xc1, 0xad, 0xd5,
	0x26, 0xee, 0x1d, 0x84, 0x2f, 0xb7, 0x8f, 0x3e, 0xb8, 0xeb, 0x7e, 0x68, 0xad, 0x16, 0x93, 0x85,
	0x05, 0x56, 0xea, 0x92, 0x21, 0x79, 0x72, 0x87, 0x69, 0x26, 0x30, 0xf0, 0x26, 0x70, 0x9f, 0xf4,
	0x54, 0x61, 0x85, 0x92, 0x3c, 0x47, 0xcb, 0x3d, 0xd6, 0xe0, 0xe4, 0xf7, 0x35, 0x12, 0x8e, 0xae,
	0x98, 0x73, 0x96, 0xaa, 0x85, 0xb4, 0x7a, 0x19, 0x07, 0xd8, 0x53, 0x0d, 0xdd, 0x79, 0x51, 0x3a,
	0xe3, 0x52, 0xfc, 0xc4, 0xdd, 0x9a, 0x78, 0x0d, 0xe9, 0x4e, 0x8d, 0x0e, 0x08, 0xf5, 0x31, 0xcf,
	0xaf, 0xa5, 0xb0, 0x71, 0x88, 0xca, 0x15, 0x8c, 0xeb, 0x28, 0x57, 0x29, 0xcf, 0x85, 0x5d, 0xc6,
	0xeb, 0xa8, 0x6a, 0xb0, 0xe3, 0x0a, 0xad, 0x5e, 0x0b, 0x99, 0xba, 0x73, 0x84, 0x5c, 0x8d, 0xe9,
	0xc7, 0x64, 0xc7, 0x58, 0x0d, 0x60, 0x87, 0xd3, 0xa9, 0x06, 0x63, 0xe2, 0x4d, 0x14, 0x74, 0x8b,
	0x78, 0xe2, 0x94, 0xb1, 0x3c, 0x77, 0x57, 0x43, 0x15, 0xb1, 0x57, 0x71, 0x8e, 0x0c, 0x68, 0xc1,
	0xf3, 0xf1, 0x62, 0x3e, 0x01, 0x8d, 0x07, 0x2e, 0x62, 0x9d, 0x9a, 0x7b, 0x46, 0xaa, 0xe6, 0x73,
	0x25, 0x71, 0xf7, 0x22, 0x54, 0x78, 0x95, 0xe3, 0x73, 0xf2, 0xa9, 0x50, 0x03, 0x90, 0x52, 0xa9,
	0x41, 0x79, 0x12, 0xbe, 0x48, 0x73, 0x01, 0xd2, 0x0e, 0xdc, 0xe7, 0x6b, 0xf9, 0xa5, 0xda, 0xec,
	0xdf, 0x71, 0x34, 0x02, 0x6d, 0x2f, 0x5d, 0xed, 0xc7, 0xf7, 0x56, 0x7c, 0xde, 0x4e, 0x36, 0x11,
	0x7f, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x0d, 0xf8, 0x48, 0x48, 0x0b, 0x00, 0x00,
}
