// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/raft/raft.proto

package raft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_OK          Type = 0
	Type_TERM        Type = 1
	Type_FOLLOW_ME   Type = 2
	Type_VOTE_ME     Type = 3
	Type_LEADER_NODE Type = 4
)

var Type_name = map[int32]string{
	0: "OK",
	1: "TERM",
	2: "FOLLOW_ME",
	3: "VOTE_ME",
	4: "LEADER_NODE",
}

var Type_value = map[string]int32{
	"OK":          0,
	"TERM":        1,
	"FOLLOW_ME":   2,
	"VOTE_ME":     3,
	"LEADER_NODE": 4,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{0}
}

type Status int32

const (
	Status_LEADER    Status = 0
	Status_FOLLOWER  Status = 1
	Status_CANDIDATE Status = 2
)

var Status_name = map[int32]string{
	0: "LEADER",
	1: "FOLLOWER",
	2: "CANDIDATE",
}

var Status_value = map[string]int32{
	"LEADER":    0,
	"FOLLOWER":  1,
	"CANDIDATE": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{1}
}

type Beat struct {
	Beat                 []byte   `protobuf:"bytes,1,opt,name=beat,proto3" json:"beat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Beat) Reset()         { *m = Beat{} }
func (m *Beat) String() string { return proto.CompactTextString(m) }
func (*Beat) ProtoMessage()    {}
func (*Beat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{0}
}

func (m *Beat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Beat.Unmarshal(m, b)
}
func (m *Beat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Beat.Marshal(b, m, deterministic)
}
func (m *Beat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Beat.Merge(m, src)
}
func (m *Beat) XXX_Size() int {
	return xxx_messageInfo_Beat.Size(m)
}
func (m *Beat) XXX_DiscardUnknown() {
	xxx_messageInfo_Beat.DiscardUnknown(m)
}

var xxx_messageInfo_Beat proto.InternalMessageInfo

func (m *Beat) GetBeat() []byte {
	if m != nil {
		return m.Beat
	}
	return nil
}

// ReqElection 发起选举请求对象
type ReqElection struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Term                 int32    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqElection) Reset()         { *m = ReqElection{} }
func (m *ReqElection) String() string { return proto.CompactTextString(m) }
func (*ReqElection) ProtoMessage()    {}
func (*ReqElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{1}
}

func (m *ReqElection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqElection.Unmarshal(m, b)
}
func (m *ReqElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqElection.Marshal(b, m, deterministic)
}
func (m *ReqElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqElection.Merge(m, src)
}
func (m *ReqElection) XXX_Size() int {
	return xxx_messageInfo_ReqElection.Size(m)
}
func (m *ReqElection) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqElection.DiscardUnknown(m)
}

var xxx_messageInfo_ReqElection proto.InternalMessageInfo

func (m *ReqElection) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ReqElection) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

// ReqElection 发起选举请求对象
type ReqFollow struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Term                 int32    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFollow) Reset()         { *m = ReqFollow{} }
func (m *ReqFollow) String() string { return proto.CompactTextString(m) }
func (*ReqFollow) ProtoMessage()    {}
func (*ReqFollow) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{2}
}

func (m *ReqFollow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFollow.Unmarshal(m, b)
}
func (m *ReqFollow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFollow.Marshal(b, m, deterministic)
}
func (m *ReqFollow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFollow.Merge(m, src)
}
func (m *ReqFollow) XXX_Size() int {
	return xxx_messageInfo_ReqFollow.Size(m)
}
func (m *ReqFollow) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFollow.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFollow proto.InternalMessageInfo

func (m *ReqFollow) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ReqFollow) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{3}
}

func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeMap struct {
	Nodes                map[string]*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NodeMap) Reset()         { *m = NodeMap{} }
func (m *NodeMap) String() string { return proto.CompactTextString(m) }
func (*NodeMap) ProtoMessage()    {}
func (*NodeMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{4}
}

func (m *NodeMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMap.Unmarshal(m, b)
}
func (m *NodeMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMap.Marshal(b, m, deterministic)
}
func (m *NodeMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMap.Merge(m, src)
}
func (m *NodeMap) XXX_Size() int {
	return xxx_messageInfo_NodeMap.Size(m)
}
func (m *NodeMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMap.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMap proto.InternalMessageInfo

func (m *NodeMap) GetNodes() map[string]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Http                 string   `protobuf:"bytes,3,opt,name=http,proto3" json:"http,omitempty"`
	Rpc                  string   `protobuf:"bytes,4,opt,name=rpc,proto3" json:"rpc,omitempty"`
	LastActive           int64    `protobuf:"varint,5,opt,name=lastActive,proto3" json:"lastActive,omitempty"`
	Status               Status   `protobuf:"varint,6,opt,name=status,proto3,enum=raft.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Node) GetHttp() string {
	if m != nil {
		return m.Http
	}
	return ""
}

func (m *Node) GetRpc() string {
	if m != nil {
		return m.Rpc
	}
	return ""
}

func (m *Node) GetLastActive() int64 {
	if m != nil {
		return m.LastActive
	}
	return 0
}

func (m *Node) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_LEADER
}

// ReqElection 发起选举请求对象
type Leader struct {
	BrokerID             string   `protobuf:"bytes,1,opt,name=brokerID,proto3" json:"brokerID,omitempty"`
	Term                 int32    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leader) Reset()         { *m = Leader{} }
func (m *Leader) String() string { return proto.CompactTextString(m) }
func (*Leader) ProtoMessage()    {}
func (*Leader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{6}
}

func (m *Leader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leader.Unmarshal(m, b)
}
func (m *Leader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leader.Marshal(b, m, deterministic)
}
func (m *Leader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leader.Merge(m, src)
}
func (m *Leader) XXX_Size() int {
	return xxx_messageInfo_Leader.Size(m)
}
func (m *Leader) XXX_DiscardUnknown() {
	xxx_messageInfo_Leader.DiscardUnknown(m)
}

var xxx_messageInfo_Leader proto.InternalMessageInfo

func (m *Leader) GetBrokerID() string {
	if m != nil {
		return m.BrokerID
	}
	return ""
}

func (m *Leader) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

type Resp struct {
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=raft.Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*Resp_Election
	//	*Resp_Leader
	Result               isResp_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{7}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_OK
}

type isResp_Result interface {
	isResp_Result()
}

type Resp_Election struct {
	Election *ReqElection `protobuf:"bytes,2,opt,name=election,proto3,oneof"`
}

type Resp_Leader struct {
	Leader *LeaderNode `protobuf:"bytes,3,opt,name=leader,proto3,oneof"`
}

func (*Resp_Election) isResp_Result() {}

func (*Resp_Leader) isResp_Result() {}

func (m *Resp) GetResult() isResp_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Resp) GetElection() *ReqElection {
	if x, ok := m.GetResult().(*Resp_Election); ok {
		return x.Election
	}
	return nil
}

func (m *Resp) GetLeader() *LeaderNode {
	if x, ok := m.GetResult().(*Resp_Leader); ok {
		return x.Leader
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Resp) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Resp_OneofMarshaler, _Resp_OneofUnmarshaler, _Resp_OneofSizer, []interface{}{
		(*Resp_Election)(nil),
		(*Resp_Leader)(nil),
	}
}

func _Resp_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Resp)
	// Result
	switch x := m.Result.(type) {
	case *Resp_Election:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Election); err != nil {
			return err
		}
	case *Resp_Leader:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Leader); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Resp.Result has unexpected type %T", x)
	}
	return nil
}

func _Resp_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Resp)
	switch tag {
	case 2: // Result.election
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqElection)
		err := b.DecodeMessage(msg)
		m.Result = &Resp_Election{msg}
		return true, err
	case 3: // Result.leader
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeaderNode)
		err := b.DecodeMessage(msg)
		m.Result = &Resp_Leader{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Resp_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Resp)
	// Result
	switch x := m.Result.(type) {
	case *Resp_Election:
		s := proto.Size(x.Election)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Resp_Leader:
		s := proto.Size(x.Leader)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LeaderNode struct {
	Leader               *Node    `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Term                 int32    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderNode) Reset()         { *m = LeaderNode{} }
func (m *LeaderNode) String() string { return proto.CompactTextString(m) }
func (*LeaderNode) ProtoMessage()    {}
func (*LeaderNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c753dad2b2315b5, []int{8}
}

func (m *LeaderNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderNode.Unmarshal(m, b)
}
func (m *LeaderNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderNode.Marshal(b, m, deterministic)
}
func (m *LeaderNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderNode.Merge(m, src)
}
func (m *LeaderNode) XXX_Size() int {
	return xxx_messageInfo_LeaderNode.Size(m)
}
func (m *LeaderNode) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderNode.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderNode proto.InternalMessageInfo

func (m *LeaderNode) GetLeader() *Node {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *LeaderNode) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func init() {
	proto.RegisterEnum("raft.Type", Type_name, Type_value)
	proto.RegisterEnum("raft.Status", Status_name, Status_value)
	proto.RegisterType((*Beat)(nil), "raft.Beat")
	proto.RegisterType((*ReqElection)(nil), "raft.ReqElection")
	proto.RegisterType((*ReqFollow)(nil), "raft.ReqFollow")
	proto.RegisterType((*Nodes)(nil), "raft.Nodes")
	proto.RegisterType((*NodeMap)(nil), "raft.NodeMap")
	proto.RegisterMapType((map[string]*Node)(nil), "raft.NodeMap.NodesEntry")
	proto.RegisterType((*Node)(nil), "raft.Node")
	proto.RegisterType((*Leader)(nil), "raft.Leader")
	proto.RegisterType((*Resp)(nil), "raft.Resp")
	proto.RegisterType((*LeaderNode)(nil), "raft.LeaderNode")
}

func init() { proto.RegisterFile("grpc/proto/raft/raft.proto", fileDescriptor_8c753dad2b2315b5) }

var fileDescriptor_8c753dad2b2315b5 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x66, 0x71, 0x60, 0xa0, 0xd4, 0x9d, 0x93, 0xc5, 0x21, 0xb2, 0xac, 0x1e, 0x28, 0x07,
	0x50, 0xe9, 0x25, 0xea, 0xa5, 0x22, 0xf5, 0x46, 0x89, 0xca, 0x87, 0xb4, 0x45, 0xed, 0x31, 0x5a,
	0xf0, 0xb6, 0x45, 0x71, 0xf1, 0x66, 0xbd, 0xa4, 0xe2, 0xd4, 0x5f, 0xd0, 0x6b, 0x7f, 0x6f, 0xb5,
	0xbb, 0x2e, 0xa4, 0x69, 0x4e, 0xb9, 0xc0, 0xcc, 0x9b, 0x37, 0x33, 0x6f, 0xdf, 0xae, 0xa1, 0xf7,
	0x55, 0xc9, 0xf5, 0x48, 0xaa, 0x42, 0x17, 0x23, 0xc5, 0xbf, 0x68, 0xfb, 0x33, 0xb4, 0x39, 0x12,
	0x13, 0x27, 0x3d, 0x20, 0xe7, 0x82, 0x6b, 0x44, 0x20, 0x2b, 0xc1, 0x75, 0xe4, 0xc5, 0x5e, 0xbf,
	0xc3, 0x6c, 0x9c, 0x4c, 0xa0, 0xcd, 0xc4, 0x2d, 0xcd, 0xc5, 0x5a, 0x6f, 0x8a, 0x2d, 0x9e, 0x02,
	0xd9, 0x16, 0x99, 0xb0, 0x94, 0xf6, 0x18, 0x86, 0x76, 0xd6, 0xbc, 0xc8, 0x04, 0xb3, 0xb8, 0x19,
	0xa1, 0x85, 0xfa, 0x1e, 0xf9, 0xb1, 0xd7, 0x6f, 0x30, 0x1b, 0x27, 0xef, 0xa0, 0xc5, 0xc4, 0xed,
	0x45, 0x91, 0xe7, 0xc5, 0x8f, 0x27, 0x0d, 0x78, 0x05, 0x0d, 0xc3, 0x28, 0x31, 0x86, 0x86, 0x21,
	0x95, 0x91, 0x17, 0xd7, 0x1f, 0x74, 0xbb, 0x42, 0xf2, 0x13, 0x4e, 0x4c, 0x3a, 0xe3, 0x12, 0x87,
	0xff, 0x92, 0xa3, 0x23, 0x79, 0xc6, 0xa5, 0xfd, 0x2f, 0xe9, 0x56, 0xab, 0x7d, 0xd5, 0xda, 0x4b,
	0x01, 0x8e, 0x20, 0x86, 0x50, 0xbf, 0x11, 0x7b, 0x2b, 0xb3, 0xc5, 0x4c, 0x68, 0x96, 0xdf, 0xf1,
	0x7c, 0x27, 0xac, 0xb4, 0x07, 0xcb, 0x6d, 0xe1, 0xad, 0x7f, 0xe6, 0x25, 0xbf, 0x3d, 0x20, 0x06,
	0xc3, 0x2e, 0xf8, 0x9b, 0xac, 0xea, 0xf7, 0x37, 0x99, 0x39, 0x18, 0xcf, 0x32, 0x65, 0xbb, 0x5b,
	0xcc, 0xc6, 0x06, 0xfb, 0xa6, 0xb5, 0x8c, 0xea, 0x0e, 0x33, 0xb1, 0x59, 0xac, 0xe4, 0x3a, 0x22,
	0x6e, 0xb1, 0x92, 0x6b, 0x3c, 0x05, 0xc8, 0x79, 0xa9, 0x27, 0x6b, 0xbd, 0xb9, 0x13, 0x51, 0x23,
	0xf6, 0xfa, 0x75, 0x76, 0x0f, 0xc1, 0x97, 0x10, 0x94, 0x9a, 0xeb, 0x5d, 0x19, 0x05, 0xb1, 0xd7,
	0xef, 0x8e, 0x3b, 0x4e, 0xd9, 0x47, 0x8b, 0xb1, 0xaa, 0x96, 0x9c, 0x41, 0x30, 0x15, 0x3c, 0x13,
	0x0a, 0x7b, 0xd0, 0x5c, 0xa9, 0xe2, 0x46, 0xa8, 0xab, 0xb4, 0xd2, 0x77, 0xc8, 0x1f, 0xb5, 0xff,
	0x97, 0x07, 0x84, 0x89, 0x52, 0x9a, 0xbb, 0xd3, 0x7b, 0xe9, 0xee, 0xae, 0xfb, 0xd7, 0x80, 0xe5,
	0x5e, 0x0a, 0x66, 0x71, 0x1c, 0x41, 0x53, 0x54, 0x0f, 0xa5, 0x32, 0xe9, 0x85, 0xe3, 0xdc, 0x7b,
	0x41, 0x97, 0x35, 0x76, 0x20, 0xe1, 0x00, 0x82, 0xdc, 0x6a, 0xb2, 0x0e, 0xb4, 0xc7, 0xa1, 0xa3,
	0x3b, 0x9d, 0xc6, 0xc5, 0xcb, 0x1a, 0xab, 0x18, 0xe7, 0x4d, 0x08, 0x98, 0x28, 0x77, 0xb9, 0x4e,
	0x52, 0x80, 0x23, 0x03, 0x93, 0xc3, 0x8c, 0xff, 0x9f, 0x54, 0x55, 0x79, 0xec, 0x54, 0x03, 0x0a,
	0xc4, 0x48, 0xc7, 0x00, 0xfc, 0xc5, 0x87, 0xb0, 0x86, 0x4d, 0x20, 0x4b, 0xca, 0x66, 0xa1, 0x87,
	0xcf, 0xa0, 0x75, 0xb1, 0x98, 0x4e, 0x17, 0x9f, 0xaf, 0x67, 0x34, 0xf4, 0xb1, 0x0d, 0x27, 0x9f,
	0x16, 0x4b, 0x6a, 0x92, 0x3a, 0x3e, 0x87, 0xf6, 0x94, 0x4e, 0x52, 0xca, 0xae, 0xe7, 0x8b, 0x94,
	0x86, 0x64, 0xf0, 0x1a, 0x02, 0x67, 0x34, 0x02, 0x04, 0xae, 0x14, 0xd6, 0xb0, 0x03, 0x4d, 0x37,
	0x82, 0x32, 0x37, 0xf0, 0xfd, 0x64, 0x9e, 0x5e, 0xa5, 0x93, 0x25, 0x0d, 0xfd, 0x55, 0x60, 0xbf,
	0xbd, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x72, 0xf0, 0xe0, 0x99, 0x03, 0x00, 0x00,
}
