// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/ledger.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	kvrwset "github.com/hyperledger/fabric/protos/ledger/rwset/kvrwset"
	peer "github.com/hyperledger/fabric/protos/peer"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqInfo struct {
	ConfigID             string   `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInfo) Reset()         { *m = ReqInfo{} }
func (m *ReqInfo) String() string { return proto.CompactTextString(m) }
func (*ReqInfo) ProtoMessage()    {}
func (*ReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{0}
}

func (m *ReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInfo.Unmarshal(m, b)
}
func (m *ReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInfo.Marshal(b, m, deterministic)
}
func (m *ReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInfo.Merge(m, src)
}
func (m *ReqInfo) XXX_Size() int {
	return xxx_messageInfo_ReqInfo.Size(m)
}
func (m *ReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInfo proto.InternalMessageInfo

func (m *ReqInfo) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *ReqInfo) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type ReqBlockByHeight struct {
	ConfigID             string   `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByHeight) Reset()         { *m = ReqBlockByHeight{} }
func (m *ReqBlockByHeight) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByHeight) ProtoMessage()    {}
func (*ReqBlockByHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{1}
}

func (m *ReqBlockByHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByHeight.Unmarshal(m, b)
}
func (m *ReqBlockByHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByHeight.Marshal(b, m, deterministic)
}
func (m *ReqBlockByHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByHeight.Merge(m, src)
}
func (m *ReqBlockByHeight) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByHeight.Size(m)
}
func (m *ReqBlockByHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByHeight.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByHeight proto.InternalMessageInfo

func (m *ReqBlockByHeight) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *ReqBlockByHeight) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ReqBlockByHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ChannelInfo struct {
	Endorser             string   `protobuf:"bytes,1,opt,name=endorser,proto3" json:"endorser,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Bci                  *BCI     `protobuf:"bytes,3,opt,name=bci,proto3" json:"bci,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{2}
}

func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (m *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(m, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetEndorser() string {
	if m != nil {
		return m.Endorser
	}
	return ""
}

func (m *ChannelInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ChannelInfo) GetBci() *BCI {
	if m != nil {
		return m.Bci
	}
	return nil
}

type BCI struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	CurrentBlockHash     string   `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash    string   `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BCI) Reset()         { *m = BCI{} }
func (m *BCI) String() string { return proto.CompactTextString(m) }
func (*BCI) ProtoMessage()    {}
func (*BCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{3}
}

func (m *BCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BCI.Unmarshal(m, b)
}
func (m *BCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BCI.Marshal(b, m, deterministic)
}
func (m *BCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BCI.Merge(m, src)
}
func (m *BCI) XXX_Size() int {
	return xxx_messageInfo_BCI.Size(m)
}
func (m *BCI) XXX_DiscardUnknown() {
	xxx_messageInfo_BCI.DiscardUnknown(m)
}

var xxx_messageInfo_BCI proto.InternalMessageInfo

func (m *BCI) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BCI) GetCurrentBlockHash() string {
	if m != nil {
		return m.CurrentBlockHash
	}
	return ""
}

func (m *BCI) GetPreviousBlockHash() string {
	if m != nil {
		return m.PreviousBlockHash
	}
	return ""
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Metadata             *BlockMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Envelopes            []*Envelope    `protobuf:"bytes,5,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{4}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetMetadata() *BlockMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Block) GetEnvelopes() []*Envelope {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

type BlockHeader struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	PreviousHash         string   `protobuf:"bytes,2,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	DataHash             string   `protobuf:"bytes,3,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	EnvelopeCount        int64    `protobuf:"varint,4,opt,name=envelopeCount,proto3" json:"envelopeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{5}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *BlockHeader) GetDataHash() string {
	if m != nil {
		return m.DataHash
	}
	return ""
}

func (m *BlockHeader) GetEnvelopeCount() int64 {
	if m != nil {
		return m.EnvelopeCount
	}
	return 0
}

type Envelope struct {
	ChannelID               string                    `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Type                    int32                     `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Version                 int32                     `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp               *Timestamp                `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionID           string                    `protobuf:"bytes,5,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Epoch                   uint64                    `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Extension               string                    `protobuf:"bytes,7,opt,name=extension,proto3" json:"extension,omitempty"`
	TlsCertHash             string                    `protobuf:"bytes,8,opt,name=tlsCertHash,proto3" json:"tlsCertHash,omitempty"`
	TransactionEnvelopeInfo *Transaction              `protobuf:"bytes,9,opt,name=transactionEnvelopeInfo,proto3" json:"transactionEnvelopeInfo,omitempty"`
	CreateID                string                    `protobuf:"bytes,10,opt,name=createID,proto3" json:"createID,omitempty"`
	MspID                   string                    `protobuf:"bytes,11,opt,name=mspID,proto3" json:"mspID,omitempty"`
	Nonce                   string                    `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature               string                    `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"`
	ChainCode               *ChainCodeHeaderExtension `protobuf:"bytes,14,opt,name=chainCode,proto3" json:"chainCode,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{6}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *Envelope) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Envelope) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Envelope) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Envelope) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *Envelope) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Envelope) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *Envelope) GetTlsCertHash() string {
	if m != nil {
		return m.TlsCertHash
	}
	return ""
}

func (m *Envelope) GetTransactionEnvelopeInfo() *Transaction {
	if m != nil {
		return m.TransactionEnvelopeInfo
	}
	return nil
}

func (m *Envelope) GetCreateID() string {
	if m != nil {
		return m.CreateID
	}
	return ""
}

func (m *Envelope) GetMspID() string {
	if m != nil {
		return m.MspID
	}
	return ""
}

func (m *Envelope) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Envelope) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Envelope) GetChainCode() *ChainCodeHeaderExtension {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

type Transaction struct {
	TxCount                    int64     `protobuf:"varint,1,opt,name=txCount,proto3" json:"txCount,omitempty"`
	TransactionActionInfoArray []*Action `protobuf:"bytes,2,rep,name=transactionActionInfoArray,proto3" json:"transactionActionInfoArray,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}  `json:"-"`
	XXX_unrecognized           []byte    `json:"-"`
	XXX_sizecache              int32     `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{7}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxCount() int64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *Transaction) GetTransactionActionInfoArray() []*Action {
	if m != nil {
		return m.TransactionActionInfoArray
	}
	return nil
}

type Action struct {
	ChainCodeActionPayload *ChainCodeActionPayload `protobuf:"bytes,1,opt,name=chainCodeActionPayload,proto3" json:"chainCodeActionPayload,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{8}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetChainCodeActionPayload() *ChainCodeActionPayload {
	if m != nil {
		return m.ChainCodeActionPayload
	}
	return nil
}

type ChainCodeAction struct {
	ChainCodeID          *ChainCodeID    `protobuf:"bytes,1,opt,name=chainCodeID,proto3" json:"chainCodeID,omitempty"`
	TxRwSet              *TxRwSet        `protobuf:"bytes,2,opt,name=txRwSet,proto3" json:"txRwSet,omitempty"`
	Event                *ChainCodeEvent `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Response             *Response       `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChainCodeAction) Reset()         { *m = ChainCodeAction{} }
func (m *ChainCodeAction) String() string { return proto.CompactTextString(m) }
func (*ChainCodeAction) ProtoMessage()    {}
func (*ChainCodeAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{9}
}

func (m *ChainCodeAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeAction.Unmarshal(m, b)
}
func (m *ChainCodeAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeAction.Marshal(b, m, deterministic)
}
func (m *ChainCodeAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeAction.Merge(m, src)
}
func (m *ChainCodeAction) XXX_Size() int {
	return xxx_messageInfo_ChainCodeAction.Size(m)
}
func (m *ChainCodeAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeAction.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeAction proto.InternalMessageInfo

func (m *ChainCodeAction) GetChainCodeID() *ChainCodeID {
	if m != nil {
		return m.ChainCodeID
	}
	return nil
}

func (m *ChainCodeAction) GetTxRwSet() *TxRwSet {
	if m != nil {
		return m.TxRwSet
	}
	return nil
}

func (m *ChainCodeAction) GetEvent() *ChainCodeEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ChainCodeAction) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type TxRwSet struct {
	NsRwSets             []*NsRwSets `protobuf:"bytes,1,rep,name=nsRwSets,proto3" json:"nsRwSets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TxRwSet) Reset()         { *m = TxRwSet{} }
func (m *TxRwSet) String() string { return proto.CompactTextString(m) }
func (*TxRwSet) ProtoMessage()    {}
func (*TxRwSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{10}
}

func (m *TxRwSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRwSet.Unmarshal(m, b)
}
func (m *TxRwSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRwSet.Marshal(b, m, deterministic)
}
func (m *TxRwSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRwSet.Merge(m, src)
}
func (m *TxRwSet) XXX_Size() int {
	return xxx_messageInfo_TxRwSet.Size(m)
}
func (m *TxRwSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRwSet.DiscardUnknown(m)
}

var xxx_messageInfo_TxRwSet proto.InternalMessageInfo

func (m *TxRwSet) GetNsRwSets() []*NsRwSets {
	if m != nil {
		return m.NsRwSets
	}
	return nil
}

type NsRwSets struct {
	NameSpace            string           `protobuf:"bytes,1,opt,name=nameSpace,proto3" json:"nameSpace,omitempty"`
	KVRWSet              *kvrwset.KVRWSet `protobuf:"bytes,2,opt,name=KVRWSet,proto3" json:"KVRWSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NsRwSets) Reset()         { *m = NsRwSets{} }
func (m *NsRwSets) String() string { return proto.CompactTextString(m) }
func (*NsRwSets) ProtoMessage()    {}
func (*NsRwSets) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{11}
}

func (m *NsRwSets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NsRwSets.Unmarshal(m, b)
}
func (m *NsRwSets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NsRwSets.Marshal(b, m, deterministic)
}
func (m *NsRwSets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NsRwSets.Merge(m, src)
}
func (m *NsRwSets) XXX_Size() int {
	return xxx_messageInfo_NsRwSets.Size(m)
}
func (m *NsRwSets) XXX_DiscardUnknown() {
	xxx_messageInfo_NsRwSets.DiscardUnknown(m)
}

var xxx_messageInfo_NsRwSets proto.InternalMessageInfo

func (m *NsRwSets) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

func (m *NsRwSets) GetKVRWSet() *kvrwset.KVRWSet {
	if m != nil {
		return m.KVRWSet
	}
	return nil
}

type ChainCodeEvent struct {
	ChainCodeID          string   `protobuf:"bytes,1,opt,name=chainCodeID,proto3" json:"chainCodeID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainCodeEvent) Reset()         { *m = ChainCodeEvent{} }
func (m *ChainCodeEvent) String() string { return proto.CompactTextString(m) }
func (*ChainCodeEvent) ProtoMessage()    {}
func (*ChainCodeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{12}
}

func (m *ChainCodeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeEvent.Unmarshal(m, b)
}
func (m *ChainCodeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeEvent.Marshal(b, m, deterministic)
}
func (m *ChainCodeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeEvent.Merge(m, src)
}
func (m *ChainCodeEvent) XXX_Size() int {
	return xxx_messageInfo_ChainCodeEvent.Size(m)
}
func (m *ChainCodeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeEvent proto.InternalMessageInfo

func (m *ChainCodeEvent) GetChainCodeID() string {
	if m != nil {
		return m.ChainCodeID
	}
	return ""
}

func (m *ChainCodeEvent) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *ChainCodeEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *ChainCodeEvent) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Payload              string   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{13}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type ChainCodeActionPayload struct {
	ChainCodeProposalPayload *peer.ChaincodeInvocationSpec `protobuf:"bytes,1,opt,name=chainCodeProposalPayload,proto3" json:"chainCodeProposalPayload,omitempty"`
	ChainCodeEndorsedAction  *ChainCodeEndorsedAction      `protobuf:"bytes,2,opt,name=chainCodeEndorsedAction,proto3" json:"chainCodeEndorsedAction,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                      `json:"-"`
	XXX_unrecognized         []byte                        `json:"-"`
	XXX_sizecache            int32                         `json:"-"`
}

func (m *ChainCodeActionPayload) Reset()         { *m = ChainCodeActionPayload{} }
func (m *ChainCodeActionPayload) String() string { return proto.CompactTextString(m) }
func (*ChainCodeActionPayload) ProtoMessage()    {}
func (*ChainCodeActionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{14}
}

func (m *ChainCodeActionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeActionPayload.Unmarshal(m, b)
}
func (m *ChainCodeActionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeActionPayload.Marshal(b, m, deterministic)
}
func (m *ChainCodeActionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeActionPayload.Merge(m, src)
}
func (m *ChainCodeActionPayload) XXX_Size() int {
	return xxx_messageInfo_ChainCodeActionPayload.Size(m)
}
func (m *ChainCodeActionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeActionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeActionPayload proto.InternalMessageInfo

func (m *ChainCodeActionPayload) GetChainCodeProposalPayload() *peer.ChaincodeInvocationSpec {
	if m != nil {
		return m.ChainCodeProposalPayload
	}
	return nil
}

func (m *ChainCodeActionPayload) GetChainCodeEndorsedAction() *ChainCodeEndorsedAction {
	if m != nil {
		return m.ChainCodeEndorsedAction
	}
	return nil
}

type ChainCodeEndorsedAction struct {
	ProposalResponsePayload *ProposalResponsePayload `protobuf:"bytes,1,opt,name=proposalResponsePayload,proto3" json:"proposalResponsePayload,omitempty"`
	Endorsements            []*Endorsement           `protobuf:"bytes,2,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *ChainCodeEndorsedAction) Reset()         { *m = ChainCodeEndorsedAction{} }
func (m *ChainCodeEndorsedAction) String() string { return proto.CompactTextString(m) }
func (*ChainCodeEndorsedAction) ProtoMessage()    {}
func (*ChainCodeEndorsedAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{15}
}

func (m *ChainCodeEndorsedAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeEndorsedAction.Unmarshal(m, b)
}
func (m *ChainCodeEndorsedAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeEndorsedAction.Marshal(b, m, deterministic)
}
func (m *ChainCodeEndorsedAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeEndorsedAction.Merge(m, src)
}
func (m *ChainCodeEndorsedAction) XXX_Size() int {
	return xxx_messageInfo_ChainCodeEndorsedAction.Size(m)
}
func (m *ChainCodeEndorsedAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeEndorsedAction.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeEndorsedAction proto.InternalMessageInfo

func (m *ChainCodeEndorsedAction) GetProposalResponsePayload() *ProposalResponsePayload {
	if m != nil {
		return m.ProposalResponsePayload
	}
	return nil
}

func (m *ChainCodeEndorsedAction) GetEndorsements() []*Endorsement {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

type ProposalResponsePayload struct {
	ProposalHash         string           `protobuf:"bytes,1,opt,name=proposalHash,proto3" json:"proposalHash,omitempty"`
	ChainCodeAction      *ChainCodeAction `protobuf:"bytes,2,opt,name=chainCodeAction,proto3" json:"chainCodeAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProposalResponsePayload) Reset()         { *m = ProposalResponsePayload{} }
func (m *ProposalResponsePayload) String() string { return proto.CompactTextString(m) }
func (*ProposalResponsePayload) ProtoMessage()    {}
func (*ProposalResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{16}
}

func (m *ProposalResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalResponsePayload.Unmarshal(m, b)
}
func (m *ProposalResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalResponsePayload.Marshal(b, m, deterministic)
}
func (m *ProposalResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalResponsePayload.Merge(m, src)
}
func (m *ProposalResponsePayload) XXX_Size() int {
	return xxx_messageInfo_ProposalResponsePayload.Size(m)
}
func (m *ProposalResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalResponsePayload proto.InternalMessageInfo

func (m *ProposalResponsePayload) GetProposalHash() string {
	if m != nil {
		return m.ProposalHash
	}
	return ""
}

func (m *ProposalResponsePayload) GetChainCodeAction() *ChainCodeAction {
	if m != nil {
		return m.ChainCodeAction
	}
	return nil
}

type Endorsement struct {
	CreateID             string   `protobuf:"bytes,1,opt,name=createID,proto3" json:"createID,omitempty"`
	MspID                string   `protobuf:"bytes,2,opt,name=mspID,proto3" json:"mspID,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endorsement) Reset()         { *m = Endorsement{} }
func (m *Endorsement) String() string { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()    {}
func (*Endorsement) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{17}
}

func (m *Endorsement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorsement.Unmarshal(m, b)
}
func (m *Endorsement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorsement.Marshal(b, m, deterministic)
}
func (m *Endorsement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsement.Merge(m, src)
}
func (m *Endorsement) XXX_Size() int {
	return xxx_messageInfo_Endorsement.Size(m)
}
func (m *Endorsement) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsement.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsement proto.InternalMessageInfo

func (m *Endorsement) GetCreateID() string {
	if m != nil {
		return m.CreateID
	}
	return ""
}

func (m *Endorsement) GetMspID() string {
	if m != nil {
		return m.MspID
	}
	return ""
}

func (m *Endorsement) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type ChainCodeHeaderExtension struct {
	PayloadVisibility    string       `protobuf:"bytes,1,opt,name=payloadVisibility,proto3" json:"payloadVisibility,omitempty"`
	ChainCodeID          *ChainCodeID `protobuf:"bytes,2,opt,name=chainCodeID,proto3" json:"chainCodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChainCodeHeaderExtension) Reset()         { *m = ChainCodeHeaderExtension{} }
func (m *ChainCodeHeaderExtension) String() string { return proto.CompactTextString(m) }
func (*ChainCodeHeaderExtension) ProtoMessage()    {}
func (*ChainCodeHeaderExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{18}
}

func (m *ChainCodeHeaderExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeHeaderExtension.Unmarshal(m, b)
}
func (m *ChainCodeHeaderExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeHeaderExtension.Marshal(b, m, deterministic)
}
func (m *ChainCodeHeaderExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeHeaderExtension.Merge(m, src)
}
func (m *ChainCodeHeaderExtension) XXX_Size() int {
	return xxx_messageInfo_ChainCodeHeaderExtension.Size(m)
}
func (m *ChainCodeHeaderExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeHeaderExtension.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeHeaderExtension proto.InternalMessageInfo

func (m *ChainCodeHeaderExtension) GetPayloadVisibility() string {
	if m != nil {
		return m.PayloadVisibility
	}
	return ""
}

func (m *ChainCodeHeaderExtension) GetChainCodeID() *ChainCodeID {
	if m != nil {
		return m.ChainCodeID
	}
	return nil
}

type ChainCodeID struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainCodeID) Reset()         { *m = ChainCodeID{} }
func (m *ChainCodeID) String() string { return proto.CompactTextString(m) }
func (*ChainCodeID) ProtoMessage()    {}
func (*ChainCodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{19}
}

func (m *ChainCodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeID.Unmarshal(m, b)
}
func (m *ChainCodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeID.Marshal(b, m, deterministic)
}
func (m *ChainCodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeID.Merge(m, src)
}
func (m *ChainCodeID) XXX_Size() int {
	return xxx_messageInfo_ChainCodeID.Size(m)
}
func (m *ChainCodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeID.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeID proto.InternalMessageInfo

func (m *ChainCodeID) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChainCodeID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChainCodeID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{20}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Payload struct {
	ChannelHandler       *ChannelHandler  `protobuf:"bytes,1,opt,name=channelHandler,proto3" json:"channelHandler,omitempty"`
	SignatureHeader      *SignatureHeader `protobuf:"bytes,2,opt,name=signatureHeader,proto3" json:"signatureHeader,omitempty"`
	Transaction          *Transaction     `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{21}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetChannelHandler() *ChannelHandler {
	if m != nil {
		return m.ChannelHandler
	}
	return nil
}

func (m *Payload) GetSignatureHeader() *SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

func (m *Payload) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type ChannelHandler struct {
	ChannelID            string     `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Type                 int32      `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Version              int32      `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp            *Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxID                 string     `protobuf:"bytes,5,opt,name=txID,proto3" json:"txID,omitempty"`
	Epoch                uint64     `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Extension            string     `protobuf:"bytes,7,opt,name=extension,proto3" json:"extension,omitempty"`
	TlsCertHash          string     `protobuf:"bytes,8,opt,name=tlsCertHash,proto3" json:"tlsCertHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChannelHandler) Reset()         { *m = ChannelHandler{} }
func (m *ChannelHandler) String() string { return proto.CompactTextString(m) }
func (*ChannelHandler) ProtoMessage()    {}
func (*ChannelHandler) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{22}
}

func (m *ChannelHandler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelHandler.Unmarshal(m, b)
}
func (m *ChannelHandler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelHandler.Marshal(b, m, deterministic)
}
func (m *ChannelHandler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelHandler.Merge(m, src)
}
func (m *ChannelHandler) XXX_Size() int {
	return xxx_messageInfo_ChannelHandler.Size(m)
}
func (m *ChannelHandler) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelHandler.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelHandler proto.InternalMessageInfo

func (m *ChannelHandler) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelHandler) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ChannelHandler) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChannelHandler) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChannelHandler) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *ChannelHandler) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ChannelHandler) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *ChannelHandler) GetTlsCertHash() string {
	if m != nil {
		return m.TlsCertHash
	}
	return ""
}

type SignatureHeader struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureHeader) Reset()         { *m = SignatureHeader{} }
func (m *SignatureHeader) String() string { return proto.CompactTextString(m) }
func (*SignatureHeader) ProtoMessage()    {}
func (*SignatureHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{23}
}

func (m *SignatureHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureHeader.Unmarshal(m, b)
}
func (m *SignatureHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureHeader.Marshal(b, m, deterministic)
}
func (m *SignatureHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureHeader.Merge(m, src)
}
func (m *SignatureHeader) XXX_Size() int {
	return xxx_messageInfo_SignatureHeader.Size(m)
}
func (m *SignatureHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureHeader proto.InternalMessageInfo

func (m *SignatureHeader) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SignatureHeader) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type BlockMetadata struct {
	Metadata             []string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74d365d0c0b9044, []int{24}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetMetadata() []string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqInfo)(nil), "proto.ReqInfo")
	proto.RegisterType((*ReqBlockByHeight)(nil), "proto.ReqBlockByHeight")
	proto.RegisterType((*ChannelInfo)(nil), "proto.ChannelInfo")
	proto.RegisterType((*BCI)(nil), "proto.BCI")
	proto.RegisterType((*Block)(nil), "proto.Block")
	proto.RegisterType((*BlockHeader)(nil), "proto.BlockHeader")
	proto.RegisterType((*Envelope)(nil), "proto.Envelope")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*Action)(nil), "proto.Action")
	proto.RegisterType((*ChainCodeAction)(nil), "proto.ChainCodeAction")
	proto.RegisterType((*TxRwSet)(nil), "proto.TxRwSet")
	proto.RegisterType((*NsRwSets)(nil), "proto.NsRwSets")
	proto.RegisterType((*ChainCodeEvent)(nil), "proto.ChainCodeEvent")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*ChainCodeActionPayload)(nil), "proto.ChainCodeActionPayload")
	proto.RegisterType((*ChainCodeEndorsedAction)(nil), "proto.ChainCodeEndorsedAction")
	proto.RegisterType((*ProposalResponsePayload)(nil), "proto.ProposalResponsePayload")
	proto.RegisterType((*Endorsement)(nil), "proto.Endorsement")
	proto.RegisterType((*ChainCodeHeaderExtension)(nil), "proto.ChainCodeHeaderExtension")
	proto.RegisterType((*ChainCodeID)(nil), "proto.ChainCodeID")
	proto.RegisterType((*Timestamp)(nil), "proto.Timestamp")
	proto.RegisterType((*Payload)(nil), "proto.Payload")
	proto.RegisterType((*ChannelHandler)(nil), "proto.ChannelHandler")
	proto.RegisterType((*SignatureHeader)(nil), "proto.SignatureHeader")
	proto.RegisterType((*BlockMetadata)(nil), "proto.BlockMetadata")
}

func init() { proto.RegisterFile("grpc/proto/ledger.proto", fileDescriptor_c74d365d0c0b9044) }

var fileDescriptor_c74d365d0c0b9044 = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4b, 0x6f, 0x23, 0xc5,
	0x13, 0xd7, 0xf8, 0x91, 0xd8, 0xe5, 0xcd, 0xe3, 0xdf, 0xda, 0x7f, 0x32, 0x8a, 0x16, 0x88, 0x5a,
	0x1c, 0xa2, 0x5d, 0xb0, 0x51, 0x40, 0x7b, 0x41, 0x2b, 0xed, 0xc6, 0x89, 0x14, 0x0b, 0x76, 0x37,
	0xea, 0x84, 0x80, 0x84, 0x50, 0xd4, 0x1e, 0x77, 0xec, 0xd1, 0xda, 0xdd, 0xb3, 0xd3, 0x6d, 0x27,
	0xbe, 0xc0, 0x57, 0xe0, 0x00, 0x9f, 0x82, 0x2f, 0xc1, 0x9d, 0x03, 0x9f, 0x06, 0xce, 0xa8, 0x5f,
	0xf3, 0x4a, 0x8c, 0x00, 0x09, 0x71, 0xf2, 0x54, 0xd5, 0xaf, 0xeb, 0xd5, 0xd5, 0x55, 0x65, 0xd8,
	0x1d, 0xa7, 0x49, 0xd4, 0x4b, 0x52, 0xa1, 0x44, 0x6f, 0xca, 0x46, 0x63, 0x96, 0x76, 0x0d, 0x81,
	0x9a, 0xe6, 0x67, 0xef, 0xf5, 0x82, 0xf1, 0x91, 0x48, 0x7b, 0xe3, 0x58, 0x4d, 0xe6, 0xc3, 0x6e,
	0x24, 0x66, 0xbd, 0xc9, 0x32, 0x61, 0xa9, 0xc5, 0xf6, 0xae, 0xe9, 0x30, 0x8d, 0xdd, 0x79, 0xe9,
	0x14, 0xf4, 0xd2, 0x1b, 0xc9, 0x54, 0xef, 0xcd, 0xc2, 0xff, 0x5e, 0x99, 0x0f, 0xab, 0x77, 0xef,
	0xf9, 0xdf, 0x51, 0x98, 0x30, 0x96, 0xf6, 0xa2, 0x09, 0x8d, 0x79, 0x24, 0x46, 0xcc, 0x6a, 0xc0,
	0x7d, 0x58, 0x27, 0xec, 0xed, 0x80, 0x5f, 0x0b, 0xb4, 0x07, 0xad, 0x48, 0xf0, 0xeb, 0x78, 0x3c,
	0x38, 0x0e, 0x83, 0xfd, 0xe0, 0xa0, 0x4d, 0x32, 0x1a, 0x3d, 0x82, 0x76, 0x34, 0xa1, 0x9c, 0xb3,
	0xe9, 0xe0, 0x38, 0xac, 0x19, 0x61, 0xce, 0xc0, 0x23, 0xd8, 0x26, 0xec, 0xed, 0xd1, 0x54, 0x44,
	0x6f, 0x8e, 0x96, 0xa7, 0x2c, 0x1e, 0x4f, 0xd4, 0x3f, 0xd7, 0x86, 0x76, 0x60, 0x6d, 0x62, 0x74,
	0x84, 0xf5, 0xfd, 0xe0, 0xa0, 0x4e, 0x1c, 0x85, 0xaf, 0xa0, 0xd3, 0x77, 0x20, 0xe7, 0xae, 0x09,
	0x5e, 0xb2, 0xd4, 0x1b, 0xf0, 0xb4, 0x56, 0x21, 0x15, 0x55, 0x73, 0x69, 0xb4, 0x37, 0x89, 0xa3,
	0xd0, 0x23, 0xa8, 0x0f, 0xa3, 0xd8, 0xe8, 0xed, 0x1c, 0x82, 0x4d, 0x41, 0xf7, 0xa8, 0x3f, 0x20,
	0x9a, 0x8d, 0x6f, 0xa0, 0x7e, 0xd4, 0x1f, 0x14, 0xec, 0x6b, 0xb5, 0x0d, 0x6f, 0x1f, 0x3d, 0x86,
	0xed, 0x68, 0x9e, 0xa6, 0x8c, 0x2b, 0x13, 0xe9, 0x29, 0x95, 0x13, 0xe7, 0xfc, 0x1d, 0x3e, 0xfa,
	0x00, 0xfe, 0x97, 0xa4, 0x6c, 0x11, 0x8b, 0xb9, 0xcc, 0xc1, 0x75, 0x03, 0xbe, 0x2b, 0xc0, 0x3f,
	0x04, 0xd0, 0x34, 0x14, 0x7a, 0xac, 0x6d, 0xd3, 0x11, 0x4b, 0x8d, 0xe6, 0xce, 0x21, 0xf2, 0x3e,
	0x1a, 0xac, 0x91, 0x10, 0x87, 0x40, 0x1f, 0x41, 0x6b, 0xc6, 0x14, 0x1d, 0x51, 0x45, 0xc3, 0x86,
	0x41, 0x3f, 0x2c, 0xa2, 0x5f, 0x3a, 0x19, 0xc9, 0x50, 0xe8, 0x43, 0x68, 0x33, 0xbe, 0x60, 0x53,
	0x91, 0x30, 0x19, 0x36, 0xf7, 0xeb, 0x07, 0x9d, 0xc3, 0x2d, 0x77, 0xe4, 0xc4, 0xf1, 0x49, 0x8e,
	0xc0, 0x3f, 0x06, 0xd0, 0x29, 0x18, 0x46, 0xfb, 0xd0, 0x19, 0x6a, 0xf2, 0xd5, 0x7c, 0x36, 0x74,
	0x49, 0x6f, 0x90, 0x22, 0x0b, 0x61, 0x78, 0xe0, 0xa3, 0x2b, 0xa4, 0xa7, 0xc4, 0xd3, 0xf7, 0xa6,
	0x9d, 0x29, 0x64, 0x24, 0xa3, 0xd1, 0xfb, 0xb0, 0xe1, 0xcd, 0xf7, 0xc5, 0x9c, 0x2b, 0x13, 0x57,
	0x9d, 0x94, 0x99, 0xf8, 0xb7, 0x3a, 0xb4, 0xbc, 0xbf, 0xe5, 0x5a, 0x0a, 0xaa, 0xb5, 0x84, 0xa0,
	0xa1, 0x96, 0x09, 0x73, 0x65, 0x60, 0xbe, 0x51, 0x08, 0xeb, 0x0b, 0x96, 0xca, 0x58, 0x70, 0x63,
	0xbf, 0x49, 0x3c, 0x89, 0xba, 0xd0, 0x56, 0xf1, 0x8c, 0x49, 0x45, 0x67, 0x89, 0x4b, 0xe9, 0xb6,
	0xcb, 0xcf, 0x85, 0xe7, 0x93, 0x1c, 0xa2, 0xdd, 0x55, 0x29, 0xe5, 0x92, 0x46, 0x2a, 0x16, 0x7c,
	0x70, 0x1c, 0x36, 0x8d, 0xfd, 0x32, 0x13, 0x3d, 0x84, 0x26, 0x4b, 0x44, 0x34, 0x09, 0xd7, 0x4c,
	0xc2, 0x2c, 0xa1, 0xfd, 0x66, 0xb7, 0x8a, 0x71, 0xe3, 0xc7, 0xba, 0xf5, 0x3b, 0x63, 0xe8, 0x54,
	0xab, 0xa9, 0xec, 0xb3, 0x54, 0x99, 0x3c, 0xb5, 0x8c, 0xbc, 0xc8, 0x42, 0x9f, 0xc3, 0x6e, 0xc1,
	0x8c, 0x4f, 0x87, 0x7e, 0x19, 0x61, 0xbb, 0x54, 0x3a, 0x17, 0x39, 0x8a, 0xac, 0x3a, 0x62, 0x5e,
	0x6b, 0xca, 0xa8, 0x62, 0x83, 0xe3, 0x10, 0xdc, 0x6b, 0x75, 0xb4, 0xf6, 0x7f, 0x26, 0x93, 0xc1,
	0x71, 0xd8, 0x31, 0x02, 0x4b, 0x68, 0x2e, 0x17, 0x3c, 0x62, 0xe1, 0x03, 0xcb, 0x35, 0x84, 0x8e,
	0x4a, 0xc6, 0x63, 0x4e, 0xd5, 0x3c, 0x65, 0xe1, 0x86, 0x8d, 0x2a, 0x63, 0xa0, 0x67, 0xe6, 0xae,
	0x62, 0xde, 0x17, 0x23, 0x16, 0x6e, 0x1a, 0x2f, 0xdf, 0x73, 0x5e, 0xf6, 0x3d, 0xdf, 0xd6, 0xda,
	0x89, 0xcf, 0x04, 0xc9, 0x4f, 0xe0, 0x05, 0x74, 0x0a, 0xc1, 0xe8, 0x7b, 0x54, 0xb7, 0xb6, 0x4c,
	0x02, 0x53, 0x26, 0x9e, 0x44, 0x2f, 0x61, 0xaf, 0x10, 0xe8, 0x0b, 0x7b, 0x11, 0xfc, 0x5a, 0xbc,
	0x48, 0x53, 0xba, 0x0c, 0x6b, 0xa6, 0xf0, 0x37, 0x9c, 0x61, 0x2b, 0x25, 0x7f, 0x72, 0x00, 0x5f,
	0xc1, 0x9a, 0x65, 0xa1, 0x2f, 0x60, 0x27, 0x73, 0xc7, 0xb2, 0xce, 0xe8, 0x72, 0x2a, 0xe8, 0xc8,
	0x78, 0xd0, 0x39, 0x7c, 0xa7, 0x1a, 0x4d, 0x09, 0x44, 0x56, 0x1c, 0xc6, 0xbf, 0x04, 0xb0, 0x55,
	0x39, 0x82, 0x3e, 0x81, 0x4e, 0x86, 0x76, 0x95, 0x9d, 0xdf, 0x69, 0x3f, 0x97, 0x90, 0x22, 0x0c,
	0x1d, 0xe8, 0x9c, 0x90, 0x9b, 0x73, 0xa6, 0x5c, 0x03, 0xd9, 0xf4, 0x55, 0x60, 0xb9, 0xc4, 0x8b,
	0xd1, 0x13, 0x68, 0xb2, 0x05, 0xe3, 0xca, 0x35, 0xc3, 0xff, 0x57, 0x35, 0x9f, 0x68, 0x21, 0xb1,
	0x18, 0xf4, 0x04, 0x5a, 0x29, 0x93, 0x89, 0xe0, 0x92, 0xb9, 0x77, 0xe1, 0xfb, 0x06, 0x71, 0x6c,
	0x92, 0x01, 0xf0, 0x53, 0x58, 0xbf, 0xc8, 0x8c, 0xb4, 0xb8, 0x34, 0x9f, 0x32, 0x0c, 0x4a, 0xfd,
	0xe6, 0x95, 0x63, 0x93, 0x0c, 0x80, 0x2f, 0xa0, 0xe5, 0xb9, 0xba, 0x8e, 0x38, 0x9d, 0xb1, 0xf3,
	0x84, 0x46, 0xcc, 0xbf, 0xea, 0x8c, 0x81, 0x1e, 0xc3, 0xfa, 0x67, 0x97, 0xe4, 0xcb, 0x3c, 0xca,
	0xed, 0xae, 0x1b, 0x90, 0x5d, 0xc7, 0x27, 0x1e, 0x80, 0xbf, 0x0f, 0x60, 0xb3, 0x1c, 0x94, 0x7e,
	0x5c, 0xd5, 0xd4, 0xb6, 0xcb, 0x69, 0xbc, 0xf3, 0xb0, 0x6b, 0xf7, 0x3d, 0x6c, 0xfd, 0x84, 0xb5,
	0xc2, 0x57, 0x74, 0xc6, 0x5c, 0x2b, 0xcb, 0x19, 0xba, 0x3c, 0x13, 0x57, 0x1c, 0x0d, 0x23, 0xf3,
	0x24, 0xbe, 0x84, 0x96, 0x4f, 0x9b, 0x1e, 0x36, 0xe7, 0x76, 0x52, 0x05, 0x76, 0x52, 0x59, 0x4a,
	0x9f, 0x7e, 0xc9, 0xa4, 0xa4, 0x63, 0xe6, 0x6c, 0x7b, 0x52, 0x4b, 0x7c, 0xd1, 0x59, 0x9b, 0x9e,
	0xc4, 0xbf, 0x06, 0xb0, 0x73, 0x7f, 0xe5, 0xa1, 0xaf, 0x21, 0xcc, 0xe2, 0x3b, 0x4b, 0x45, 0x22,
	0x24, 0x9d, 0x96, 0x4b, 0xd7, 0x3d, 0x44, 0x69, 0x2b, 0x40, 0x6f, 0x08, 0x03, 0xbe, 0x10, 0x11,
	0xd5, 0x5a, 0xce, 0x13, 0x16, 0x91, 0x95, 0x0a, 0xd0, 0x57, 0xb0, 0x9b, 0xc9, 0x4e, 0xec, 0x08,
	0x1e, 0x59, 0xf3, 0xee, 0x7a, 0xde, 0xbd, 0x53, 0x5c, 0x25, 0x14, 0x59, 0x75, 0x1c, 0xff, 0x14,
	0xc0, 0xee, 0x8a, 0x43, 0xda, 0x6a, 0xe2, 0x1c, 0xf1, 0xd9, 0x2c, 0x47, 0xe4, 0xad, 0x9e, 0xdd,
	0x8f, 0x22, 0xab, 0x8e, 0xa3, 0xa7, 0xf0, 0xc0, 0x6d, 0x12, 0x33, 0xc6, 0x95, 0x74, 0x0d, 0x03,
	0x65, 0x93, 0x32, 0x13, 0x91, 0x12, 0x0e, 0x7f, 0x07, 0xbb, 0x2b, 0x6c, 0xd9, 0xc1, 0x68, 0x45,
	0xa6, 0xa1, 0x07, 0x7e, 0x30, 0xe6, 0x3c, 0xf4, 0x1c, 0xb6, 0x2a, 0xfd, 0xc1, 0xa5, 0x6f, 0xe7,
	0xfe, 0xae, 0x42, 0xaa, 0x70, 0xfc, 0x0d, 0x74, 0x0a, 0xde, 0x95, 0x9a, 0x7a, 0xb0, 0xaa, 0xa9,
	0xd7, 0x8a, 0x4d, 0xbd, 0xd4, 0xbe, 0xeb, 0x95, 0xf6, 0x8d, 0xbf, 0x85, 0x70, 0x55, 0x9b, 0x36,
	0x0b, 0x8f, 0x8d, 0xf5, 0x32, 0x96, 0xf1, 0x30, 0x9e, 0xc6, 0x6a, 0xe9, 0x8c, 0xde, 0x15, 0x54,
	0x9b, 0x5b, 0xed, 0x2f, 0x35, 0x37, 0xfc, 0xda, 0x2c, 0x80, 0xd9, 0x23, 0x45, 0xd0, 0x48, 0xa8,
	0xf2, 0xb9, 0x34, 0xdf, 0x9a, 0xa7, 0xdb, 0x84, 0x8b, 0xca, 0x7c, 0x57, 0xe7, 0x7d, 0x3b, 0x9b,
	0xf7, 0xf8, 0x53, 0x68, 0x67, 0x73, 0x5d, 0xc3, 0x24, 0x8b, 0x04, 0x1f, 0x49, 0x3f, 0x4e, 0x1c,
	0x69, 0x46, 0x1d, 0xe5, 0xc2, 0x2f, 0x93, 0x96, 0xc0, 0x3f, 0x07, 0xd9, 0x43, 0x44, 0xcf, 0x60,
	0xd3, 0xed, 0x1c, 0xa7, 0x94, 0x8f, 0xa6, 0x6e, 0x39, 0x2a, 0x75, 0xd5, 0x82, 0x90, 0x54, 0xc0,
	0xfa, 0xe6, 0xb3, 0x2c, 0x9f, 0x16, 0xd7, 0x3f, 0x7f, 0xf3, 0xe7, 0x65, 0x29, 0xa9, 0xc2, 0x75,
	0x42, 0x0b, 0xbd, 0xc9, 0xf5, 0xf4, 0xfb, 0x36, 0x80, 0x22, 0x0c, 0xff, 0x6e, 0x7b, 0x63, 0xd1,
	0x95, 0xff, 0x72, 0x9d, 0xd2, 0xda, 0x6f, 0xb3, 0x2d, 0xca, 0x7c, 0xff, 0x3b, 0xcb, 0x13, 0x7e,
	0x01, 0x5b, 0x95, 0x94, 0xea, 0x30, 0xcc, 0xe3, 0x10, 0xfe, 0xdf, 0x84, 0x27, 0xf3, 0x4d, 0xa7,
	0x56, 0xd8, 0x74, 0xf0, 0x13, 0xd8, 0x28, 0xad, 0xd9, 0xfa, 0xb5, 0x65, 0xeb, 0xb8, 0x9e, 0x75,
	0xed, 0x7c, 0xf1, 0x1e, 0xae, 0x99, 0xa8, 0x3f, 0xfe, 0x23, 0x00, 0x00, 0xff, 0xff, 0x15, 0x35,
	0xdb, 0x89, 0x21, 0x0e, 0x00, 0x00,
}
