// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/server.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc/proto/server.proto", fileDescriptor_9f9189b3c96cae45) }

var fileDescriptor_9f9189b3c96cae45 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xda, 0x40,
	0x14, 0x85, 0x5d, 0x44, 0xa1, 0xdc, 0x16, 0x84, 0x6e, 0x5b, 0xd1, 0x7a, 0xe9, 0x4d, 0x55, 0x15,
	0x99, 0x8a, 0x56, 0x55, 0x97, 0x2d, 0xc3, 0x22, 0x8e, 0xd8, 0xe4, 0xef, 0x01, 0x1c, 0xfb, 0xc6,
	0xb6, 0xb0, 0x66, 0xc8, 0x78, 0x40, 0xe1, 0x1d, 0xb2, 0xcf, 0xc3, 0xe5, 0x65, 0xa2, 0xb1, 0x07,
	0xe3, 0x1f, 0x16, 0x59, 0x59, 0xf7, 0x7c, 0xe7, 0x9e, 0x33, 0xa3, 0x31, 0x4c, 0x22, 0xb9, 0x09,
	0x66, 0x1b, 0x29, 0x94, 0x98, 0x65, 0x24, 0x77, 0x24, 0xdd, 0x7c, 0xc0, 0xb7, 0xf9, 0xc7, 0xae,
	0x72, 0x49, 0xd9, 0x36, 0x55, 0x05, 0xb7, 0xbf, 0x54, 0x40, 0x10, 0xfb, 0x9c, 0x53, 0x6a, 0x88,
	0x5d, 0x27, 0x09, 0x0f, 0x44, 0x48, 0x6e, 0x3b, 0x2e, 0xa5, 0x30, 0x3a, 0xd4, 0xcd, 0x9f, 0xde,
	0x40, 0x9f, 0x15, 0x31, 0x38, 0x83, 0x1e, 0x93, 0xe4, 0x2b, 0xc2, 0x4f, 0x05, 0x75, 0x0d, 0x29,
	0x54, 0x7b, 0x68, 0xd4, 0x2b, 0x25, 0x13, 0x1e, 0x39, 0x16, 0xfe, 0x80, 0xee, 0xb9, 0x48, 0x38,
	0x62, 0xdd, 0xae, 0xb5, 0xb6, 0xd9, 0x85, 0xee, 0x2a, 0xc9, 0x54, 0xd3, 0xac, 0x35, 0x7b, 0x5c,
	0x33, 0xff, 0x97, 0xd2, 0xb1, 0xe6, 0xcf, 0x1d, 0x18, 0x30, 0x7d, 0x0d, 0x26, 0x42, 0xc2, 0x29,
	0x0c, 0x3c, 0x9e, 0x29, 0x3f, 0x4d, 0x19, 0xc3, 0x91, 0xb1, 0x1b, 0xa5, 0xdd, 0xf5, 0x13, 0xde,
	0x1b, 0x46, 0x21, 0x63, 0x38, 0xae, 0xfb, 0x29, 0x2c, 0x37, 0x18, 0xd3, 0xfd, 0x8e, 0x85, 0xbf,
	0x61, 0x98, 0x53, 0xae, 0x12, 0x5f, 0x11, 0x63, 0xe5, 0x31, 0x2b, 0x6a, 0xbb, 0xe7, 0x0f, 0x8c,
	0x2a, 0x5c, 0x57, 0x7d, 0x6c, 0xaf, 0x9d, 0x68, 0x9b, 0xc2, 0xe0, 0x66, 0x13, 0x49, 0x3f, 0xa4,
	0xca, 0x6d, 0x8c, 0xd2, 0x6e, 0xf9, 0x0e, 0xef, 0x3c, 0xbe, 0x13, 0x6b, 0x6d, 0x1e, 0x96, 0xf9,
	0x5a, 0xb0, 0x3f, 0x98, 0x71, 0xb1, 0x57, 0x94, 0x39, 0x16, 0x7e, 0x83, 0xfe, 0xc5, 0x96, 0xe4,
	0x9e, 0x31, 0x3c, 0xa0, 0x7c, 0x6e, 0x1a, 0xe7, 0x8f, 0x1d, 0xe8, 0xad, 0xf2, 0x1f, 0x01, 0xff,
	0xc2, 0xb8, 0xd8, 0x29, 0x1e, 0xc4, 0xe3, 0x77, 0xa2, 0x3c, 0xd3, 0x25, 0xdd, 0xeb, 0xd9, 0x6e,
	0x3c, 0x9a, 0xd6, 0x1c, 0x0b, 0x97, 0xf0, 0xb5, 0xba, 0xb9, 0x48, 0x45, 0xb0, 0x5e, 0xec, 0xcf,
	0x28, 0x89, 0x62, 0x85, 0x93, 0x63, 0x44, 0x0d, 0x1c, 0x8f, 0xa2, 0x55, 0xc7, 0xc2, 0x7f, 0x30,
	0x39, 0x95, 0xe2, 0x67, 0x31, 0x7e, 0x6e, 0x67, 0xf8, 0x59, 0xfc, 0xca, 0x84, 0xeb, 0x07, 0x6f,
	0x79, 0x22, 0x41, 0xcb, 0xcd, 0x84, 0xdb, 0x5e, 0x3e, 0xfe, 0x7a, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x54, 0x84, 0x5e, 0x36, 0x97, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChannelClient is the client API for Channel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelClient interface {
	Create(ctx context.Context, in *ChannelCreate, opts ...grpc.CallOption) (*String, error)
	Join(ctx context.Context, in *ChannelJoin, opts ...grpc.CallOption) (*String, error)
	List(ctx context.Context, in *ChannelList, opts ...grpc.CallOption) (*StringArr, error)
}

type channelClient struct {
	cc *grpc.ClientConn
}

func NewChannelClient(cc *grpc.ClientConn) ChannelClient {
	return &channelClient{cc}
}

func (c *channelClient) Create(ctx context.Context, in *ChannelCreate, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/proto.Channel/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) Join(ctx context.Context, in *ChannelJoin, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/proto.Channel/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) List(ctx context.Context, in *ChannelList, opts ...grpc.CallOption) (*StringArr, error) {
	out := new(StringArr)
	err := c.cc.Invoke(ctx, "/proto.Channel/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServer is the server API for Channel service.
type ChannelServer interface {
	Create(context.Context, *ChannelCreate) (*String, error)
	Join(context.Context, *ChannelJoin) (*String, error)
	List(context.Context, *ChannelList) (*StringArr, error)
}

func RegisterChannelServer(s *grpc.Server, srv ChannelServer) {
	s.RegisterService(&_Channel_serviceDesc, srv)
}

func _Channel_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Channel/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Create(ctx, req.(*ChannelCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Channel/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Join(ctx, req.(*ChannelJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Channel/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).List(ctx, req.(*ChannelList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Channel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Channel",
	HandlerType: (*ChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Channel_Create_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Channel_Join_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Channel_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/server.proto",
}

// ChainCodeClient is the client API for ChainCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainCodeClient interface {
	InstallCC(ctx context.Context, in *Install, opts ...grpc.CallOption) (*String, error)
	InstalledCC(ctx context.Context, in *Installed, opts ...grpc.CallOption) (*CCList, error)
	InstantiateCC(ctx context.Context, in *Instantiate, opts ...grpc.CallOption) (*String, error)
	InstantiatedCC(ctx context.Context, in *Instantiated, opts ...grpc.CallOption) (*CCList, error)
	UpgradeCC(ctx context.Context, in *Upgrade, opts ...grpc.CallOption) (*String, error)
	InvokeCC(ctx context.Context, in *Invoke, opts ...grpc.CallOption) (*Bytes, error)
	QueryCC(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Bytes, error)
}

type chainCodeClient struct {
	cc *grpc.ClientConn
}

func NewChainCodeClient(cc *grpc.ClientConn) ChainCodeClient {
	return &chainCodeClient{cc}
}

func (c *chainCodeClient) InstallCC(ctx context.Context, in *Install, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/InstallCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) InstalledCC(ctx context.Context, in *Installed, opts ...grpc.CallOption) (*CCList, error) {
	out := new(CCList)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/InstalledCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) InstantiateCC(ctx context.Context, in *Instantiate, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/InstantiateCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) InstantiatedCC(ctx context.Context, in *Instantiated, opts ...grpc.CallOption) (*CCList, error) {
	out := new(CCList)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/InstantiatedCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) UpgradeCC(ctx context.Context, in *Upgrade, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/UpgradeCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) InvokeCC(ctx context.Context, in *Invoke, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/InvokeCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainCodeClient) QueryCC(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/proto.ChainCode/QueryCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainCodeServer is the server API for ChainCode service.
type ChainCodeServer interface {
	InstallCC(context.Context, *Install) (*String, error)
	InstalledCC(context.Context, *Installed) (*CCList, error)
	InstantiateCC(context.Context, *Instantiate) (*String, error)
	InstantiatedCC(context.Context, *Instantiated) (*CCList, error)
	UpgradeCC(context.Context, *Upgrade) (*String, error)
	InvokeCC(context.Context, *Invoke) (*Bytes, error)
	QueryCC(context.Context, *Query) (*Bytes, error)
}

func RegisterChainCodeServer(s *grpc.Server, srv ChainCodeServer) {
	s.RegisterService(&_ChainCode_serviceDesc, srv)
}

func _ChainCode_InstallCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Install)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).InstallCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/InstallCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).InstallCC(ctx, req.(*Install))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_InstalledCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Installed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).InstalledCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/InstalledCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).InstalledCC(ctx, req.(*Installed))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_InstantiateCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instantiate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).InstantiateCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/InstantiateCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).InstantiateCC(ctx, req.(*Instantiate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_InstantiatedCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instantiated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).InstantiatedCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/InstantiatedCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).InstantiatedCC(ctx, req.(*Instantiated))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_UpgradeCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Upgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).UpgradeCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/UpgradeCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).UpgradeCC(ctx, req.(*Upgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_InvokeCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).InvokeCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/InvokeCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).InvokeCC(ctx, req.(*Invoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainCode_QueryCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainCodeServer).QueryCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChainCode/QueryCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainCodeServer).QueryCC(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainCode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChainCode",
	HandlerType: (*ChainCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallCC",
			Handler:    _ChainCode_InstallCC_Handler,
		},
		{
			MethodName: "InstalledCC",
			Handler:    _ChainCode_InstalledCC_Handler,
		},
		{
			MethodName: "InstantiateCC",
			Handler:    _ChainCode_InstantiateCC_Handler,
		},
		{
			MethodName: "InstantiatedCC",
			Handler:    _ChainCode_InstantiatedCC_Handler,
		},
		{
			MethodName: "UpgradeCC",
			Handler:    _ChainCode_UpgradeCC_Handler,
		},
		{
			MethodName: "InvokeCC",
			Handler:    _ChainCode_InvokeCC_Handler,
		},
		{
			MethodName: "QueryCC",
			Handler:    _ChainCode_QueryCC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/server.proto",
}

// LedgerClient is the client API for Ledger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerClient interface {
	QueryChannelInfo(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*ChannelInfo, error)
	QueryChannelBlockByHeight(ctx context.Context, in *ReqBlockByHeight, opts ...grpc.CallOption) (*Block, error)
	QueryChannelBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*Block, error)
	QueryChannelBlockByTxID(ctx context.Context, in *ReqBlockByTxID, opts ...grpc.CallOption) (*Block, error)
}

type ledgerClient struct {
	cc *grpc.ClientConn
}

func NewLedgerClient(cc *grpc.ClientConn) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) QueryChannelInfo(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*ChannelInfo, error) {
	out := new(ChannelInfo)
	err := c.cc.Invoke(ctx, "/proto.Ledger/QueryChannelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryChannelBlockByHeight(ctx context.Context, in *ReqBlockByHeight, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/proto.Ledger/QueryChannelBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryChannelBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/proto.Ledger/QueryChannelBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) QueryChannelBlockByTxID(ctx context.Context, in *ReqBlockByTxID, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/proto.Ledger/QueryChannelBlockByTxID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServer is the server API for Ledger service.
type LedgerServer interface {
	QueryChannelInfo(context.Context, *ReqInfo) (*ChannelInfo, error)
	QueryChannelBlockByHeight(context.Context, *ReqBlockByHeight) (*Block, error)
	QueryChannelBlockByHash(context.Context, *ReqBlockByHash) (*Block, error)
	QueryChannelBlockByTxID(context.Context, *ReqBlockByTxID) (*Block, error)
}

func RegisterLedgerServer(s *grpc.Server, srv LedgerServer) {
	s.RegisterService(&_Ledger_serviceDesc, srv)
}

func _Ledger_QueryChannelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryChannelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ledger/QueryChannelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryChannelInfo(ctx, req.(*ReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryChannelBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHeight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryChannelBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ledger/QueryChannelBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryChannelBlockByHeight(ctx, req.(*ReqBlockByHeight))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryChannelBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryChannelBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ledger/QueryChannelBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryChannelBlockByHash(ctx, req.(*ReqBlockByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_QueryChannelBlockByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByTxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).QueryChannelBlockByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ledger/QueryChannelBlockByTxID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).QueryChannelBlockByTxID(ctx, req.(*ReqBlockByTxID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ledger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryChannelInfo",
			Handler:    _Ledger_QueryChannelInfo_Handler,
		},
		{
			MethodName: "QueryChannelBlockByHeight",
			Handler:    _Ledger_QueryChannelBlockByHeight_Handler,
		},
		{
			MethodName: "QueryChannelBlockByHash",
			Handler:    _Ledger_QueryChannelBlockByHash_Handler,
		},
		{
			MethodName: "QueryChannelBlockByTxID",
			Handler:    _Ledger_QueryChannelBlockByTxID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/server.proto",
}
