NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.league01-org3-vh-cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.league01-org3-vh-cn-cert.pem
    OrganizationalUnitIdentifier: peer
